{
  "hash": "ee213545dea93ad26cf6ec6d31448131",
  "result": {
    "engine": "jupyter",
    "markdown": "# Exploratory Data Analysis for Financial Data\n\n::: {.callout-note}\n## Learning Objectives\nBy the end of this chapter, you should be able to:\n\n- Explain the goals of exploratory data analysis (EDA) and where it fits in the analytics workflow\n- Choose appropriate summary statistics based on a variable's level of measurement\n- Compute and interpret measures of central tendency and dispersion for financial data\n- Visually inspect the distribution of a financial variable and recognize skewness\n- Distinguish between an outlier and an error, and apply the z-score and IQR methods to flag unusual transactions\n- Perform a first-pass EDA on transaction-level general ledger data, including comparisons across categories\n:::\n\n## What Is EDA, and Why Do It First?\n\n**Exploratory data analysis (EDA)** is the process of getting to know a dataset — its shape, its typical values, its oddities — before you calculate ratios (Chapter 7), run audit tests (Chapter 8), or build a predictive model (Chapter 12). Skipping this step is one of the most common ways analytics work goes wrong: it's easy to compute a technically correct number from data you don't actually understand yet, and end up with a confidently wrong conclusion.\n\nThe EDA mindset is simple: **look before you calculate.** Let the data surprise you before you start asking it questions.\n\nThis chapter introduces EDA using a new dataset: `general_ledger_large.csv`, a simulated general ledger with **1,504 transaction lines** (752 journal entries) spanning a full fiscal year. It's large enough to show real distribution shapes and genuine outliers — something our earlier 10–20 row samples were too small to demonstrate convincingly.\n\n::: {.panel-tabset}\n## pandas\n\n::: {#7ea37198 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\ngl_pd = pd.read_csv(\"data/general_ledger_large.csv\")\nprint(gl_pd.shape)\ngl_pd.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(1504, 7)\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>entry_id</th>\n      <th>entry_date</th>\n      <th>account</th>\n      <th>debit</th>\n      <th>credit</th>\n      <th>department</th>\n      <th>posted_by</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>JE3253</td>\n      <td>2025-01-01</td>\n      <td>Cost of Goods Sold</td>\n      <td>1231.76</td>\n      <td>0.00</td>\n      <td>Operations</td>\n      <td>mchen</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>JE3253</td>\n      <td>2025-01-01</td>\n      <td>Inventory</td>\n      <td>0.00</td>\n      <td>1231.76</td>\n      <td>Operations</td>\n      <td>mchen</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>JE3413</td>\n      <td>2025-01-01</td>\n      <td>Accounts Receivable</td>\n      <td>3024.76</td>\n      <td>0.00</td>\n      <td>Sales</td>\n      <td>agarcia</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>JE3413</td>\n      <td>2025-01-01</td>\n      <td>Sales Revenue</td>\n      <td>0.00</td>\n      <td>3024.76</td>\n      <td>Sales</td>\n      <td>agarcia</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>JE3476</td>\n      <td>2025-01-01</td>\n      <td>Cash</td>\n      <td>4476.03</td>\n      <td>0.00</td>\n      <td>Sales</td>\n      <td>rpatel</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars\n\n::: {#7065daee .cell execution_count=2}\n``` {.python .cell-code}\nimport polars as pl\ngl_pl = pl.read_csv(\"data/general_ledger_large.csv\")\ngl_pl.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 7)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>entry_id</th><th>entry_date</th><th>account</th><th>debit</th><th>credit</th><th>department</th><th>posted_by</th></tr><tr><td>str</td><td>str</td><td>str</td><td>f64</td><td>f64</td><td>str</td><td>str</td></tr></thead><tbody><tr><td>&quot;JE3253&quot;</td><td>&quot;2025-01-01&quot;</td><td>&quot;Cost of Goods Sold&quot;</td><td>1231.76</td><td>0.0</td><td>&quot;Operations&quot;</td><td>&quot;mchen&quot;</td></tr><tr><td>&quot;JE3253&quot;</td><td>&quot;2025-01-01&quot;</td><td>&quot;Inventory&quot;</td><td>0.0</td><td>1231.76</td><td>&quot;Operations&quot;</td><td>&quot;mchen&quot;</td></tr><tr><td>&quot;JE3413&quot;</td><td>&quot;2025-01-01&quot;</td><td>&quot;Accounts Receivable&quot;</td><td>3024.76</td><td>0.0</td><td>&quot;Sales&quot;</td><td>&quot;agarcia&quot;</td></tr><tr><td>&quot;JE3413&quot;</td><td>&quot;2025-01-01&quot;</td><td>&quot;Sales Revenue&quot;</td><td>0.0</td><td>3024.76</td><td>&quot;Sales&quot;</td><td>&quot;agarcia&quot;</td></tr><tr><td>&quot;JE3476&quot;</td><td>&quot;2025-01-01&quot;</td><td>&quot;Cash&quot;</td><td>4476.03</td><td>0.0</td><td>&quot;Sales&quot;</td><td>&quot;rpatel&quot;</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\n## Choosing the Right Summary Statistic\n\nRecall from Chapter 3 that a variable's **level of measurement** determines which calculations are actually meaningful:\n\n| Level | Example in this dataset | Meaningful summary |\n|---|---|---|\n| Nominal | `account`, `department`, `posted_by` | Count, mode |\n| Ratio | `debit`, `credit` | Mean, median, std, all arithmetic |\n\nIt's worth pausing on this before diving into code. `department` is nominal — Sales, Operations, HR, Finance are categories with no inherent order. Computing an \"average department\" is meaningless. `debit`, on the other hand, is ratio-level — dollar amounts have a true zero and every arithmetic operation applies. The rest of this chapter focuses on summarizing `debit` and `credit`, and *counting* (not averaging) categorical fields like `department`.\n\n::: {.panel-tabset}\n## pandas\n\n::: {#ee56bc25 .cell execution_count=3}\n``` {.python .cell-code}\ngl_pd[\"department\"].value_counts()\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\ndepartment\nOperations    700\nSales         572\nHR            132\nFinance       100\nName: count, dtype: int64\n```\n:::\n:::\n\n\n## polars\n\n::: {#5aad487e .cell execution_count=4}\n``` {.python .cell-code}\ngl_pl['department'].value_counts()\n# or\ngl_pl.select(pl.col(\"department\").value_counts())\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (4, 1)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>department</th></tr><tr><td>struct[2]</td></tr></thead><tbody><tr><td>{&quot;HR&quot;,132}</td></tr><tr><td>{&quot;Finance&quot;,100}</td></tr><tr><td>{&quot;Operations&quot;,700}</td></tr><tr><td>{&quot;Sales&quot;,572}</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\n\n## Measures of Central Tendency\n\nLet's compute the mean, median, and mode of transaction debit amounts (restricting to rows where a debit actually occurred, since half the rows in a double-entry dataset have a debit of `0`).\n\n::: {.panel-tabset}\n## pandas\n\n::: {#5ae7393f .cell execution_count=5}\n``` {.python .cell-code}\ndebit_pd = gl_pd[gl_pd[\"debit\"] > 0][\"debit\"]\n\nprint(\"Mean:  \", debit_pd.mean())\nprint(\"Median:\", debit_pd.median())\nprint(\"Mode:  \", debit_pd.mode().iloc[0])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean:   4044.065132978723\nMedian: 2457.11\nMode:   1739.52\n```\n:::\n:::\n\n\n## polars\n\n::: {#4357738c .cell execution_count=6}\n``` {.python .cell-code}\ndebit_pl = gl_pl.filter(pl.col(\"debit\") > 0).select(\"debit\").to_series()\n\nprint(\"Mean:  \", debit_pl.mean())\nprint(\"Median:\", debit_pl.median())\nprint(\"Mode:  \", debit_pl.mode()[0])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean:   4044.0651329787233\nMedian: 2457.11\nMode:   1739.52\n```\n:::\n:::\n\n\n:::\n\nNotice the **mean ($4,044) is noticeably higher than the median ($2,457)**. This is a classic sign of a right-skewed distribution: most transactions are modest in size, but a handful of very large ones pull the mean upward. The median is a more representative \"typical transaction size\" here — a pattern you'll see constantly in financial data, and a good reason to always check both rather than reporting the mean alone.\n\n::: {.callout-tip}\n## Connect to Practice\nWhen a client or manager asks for \"the average transaction size,\" it's worth asking whether they want the mean or the median — for skewed financial data, these can tell noticeably different stories, and reporting only the mean can be misleading.\n:::\n\n## Measures of Dispersion\n\nCentral tendency tells you where the data is centered; dispersion tells you how spread out it is.\n\n::: {.panel-tabset}\n## pandas\n\n::: {#74503be6 .cell execution_count=7}\n``` {.python .cell-code}\nprint(\"Standard deviation:\", debit_pd.std())\nprint(\"Variance:          \", debit_pd.var())\n\nq1, q3 = debit_pd.quantile([0.25, 0.75])\niqr = q3 - q1\nprint(\"IQR:               \", iqr)\n\ncv = debit_pd.std() / debit_pd.mean()\nprint(\"Coefficient of variation:\", cv)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStandard deviation: 11497.579308527369\nVariance:           132194329.95587668\nIQR:                2576.855\nCoefficient of variation: 2.8430747108315333\n```\n:::\n:::\n\n\n## polars\n\n::: {#ced0fdf9 .cell execution_count=8}\n``` {.python .cell-code}\nprint(\"Standard deviation:\", debit_pl.std())\nprint(\"Variance:          \", debit_pl.var())\n\nq1_pl = debit_pl.quantile(0.25, interpolation=\"linear\")\nq3_pl = debit_pl.quantile(0.75, interpolation=\"linear\")\niqr_pl = q3_pl - q1_pl\nprint(\"IQR:               \", iqr_pl)\n\ncv_pl = debit_pl.std() / debit_pl.mean()\nprint(\"Coefficient of variation:\", cv_pl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStandard deviation: 11497.579308527369\nVariance:           132194329.95587671\nIQR:                2576.855\nCoefficient of variation: 2.843074710831533\n```\n:::\n:::\n\n\n:::\n\n::: {.callout-important}\n## Why the Coefficient of Variation?\nStandard deviation alone can't tell you whether an account is \"volatile\" in any meaningful sense, because it's on the same scale as the data itself — a standard deviation of $10,000 is huge for a Rent Expense account but unremarkable for total Sales Revenue. The **coefficient of variation** (standard deviation ÷ mean) is a unitless ratio, which makes it possible to fairly compare variability *across* accounts of very different sizes — something we'll do in the grouped EDA section below.\n:::\n\n## Understanding Distributions\n\nNumbers alone don't always reveal a distribution's shape — visualizing it does. Full charting techniques are the focus of Chapter 6, but a histogram and boxplot are useful enough that we'll use them here too.\n\n::: {#8748f420 .cell execution_count=9}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfig, axes = plt.subplots(1, 2, figsize=(11, 4))\n\naxes[0].hist(debit_pd, bins=40, color=\"#1c7c73\")\naxes[0].set_title(\"Debit Amounts — Full Range\")\naxes[0].set_xlabel(\"Debit Amount ($)\")\n\naxes[1].boxplot(debit_pd, vert=True)\naxes[1].set_title(\"Debit Amounts — Boxplot\")\naxes[1].set_ylabel(\"Debit Amount ($)\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](05-exploratory-data-analysis_files/figure-html/cell-10-output-1.png){width=1048 height=374}\n:::\n:::\n\n\n::: {.callout-warning}\n## When Outliers Hide the Distribution\nLook closely at the histogram: nearly every bar is crammed into the leftmost sliver of the chart, because a handful of very large transactions stretch the x-axis all the way out to $176,500. This is a common problem with skewed financial data — the outliers you'll learn to detect in the next section can also distort your ability to *see* the underlying distribution. A quick fix: zoom in by temporarily excluding the extreme values.\n:::\n\n::: {#f618c3a4 .cell execution_count=10}\n``` {.python .cell-code}\nzoomed = debit_pd[debit_pd < 10000]\n\nplt.figure(figsize=(6, 4))\nplt.hist(zoomed, bins=40, color=\"#c9482f\")\nplt.title(\"Debit Amounts Under $10,000 (zoomed in)\")\nplt.xlabel(\"Debit Amount ($)\")\nplt.show()\n\nprint(f\"{len(zoomed)} of {len(debit_pd)} transactions shown ({len(zoomed)/len(debit_pd):.1%})\")\n```\n\n::: {.cell-output .cell-output-display}\n![](05-exploratory-data-analysis_files/figure-html/cell-11-output-1.png){width=500 height=377}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n731 of 752 transactions shown (97.2%)\n```\n:::\n:::\n\n\nZooming in reveals what was hidden before: a right-skewed but otherwise unimodal (single-peaked) distribution, with most transactions clustered in the low thousands of dollars. This confirms numerically what we already suspected from the mean-vs-median gap: **skewness**, not a data error, largely explains the shape.\n\n::: {.callout-tip}\n## Connect to Practice\nA **bimodal** distribution (two distinct peaks) in an account balance often signals that two different populations have been lumped into one account — for example, a \"Travel Expense\" account mixing routine local travel with occasional expensive international trips. Spotting this kind of pattern is often the first clue that a variable needs to be split or segmented before further analysis.\n:::\n\n## Detecting Outliers\n\nAn **outlier** is a value that differs substantially from the rest of the data. Whether it's a *mistake* or a *legitimate rare event* is a judgment call — statistics can only flag candidates for you to investigate, not make that determination on its own.\n\n### The Z-Score Method\n\nA z-score measures how many standard deviations a value is from the mean. A common rule of thumb flags anything with `|z| > 3` as an outlier.\n\n::: {.panel-tabset}\n## pandas\n\n::: {#a5183fc1 .cell execution_count=11}\n``` {.python .cell-code}\nz_scores = (debit_pd - debit_pd.mean()) / debit_pd.std()\noutliers_z_pd = gl_pd.loc[debit_pd.index][z_scores.abs() > 3]\noutliers_z_pd[[\"entry_id\", \"entry_date\", \"account\", \"debit\", \"department\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>entry_id</th>\n      <th>entry_date</th>\n      <th>account</th>\n      <th>debit</th>\n      <th>department</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>322</th>\n      <td>JE3900</td>\n      <td>2025-03-14</td>\n      <td>Accounts Receivable</td>\n      <td>145000.0</td>\n      <td>Sales</td>\n    </tr>\n    <tr>\n      <th>458</th>\n      <td>JE3901</td>\n      <td>2025-04-22</td>\n      <td>Cash</td>\n      <td>98000.0</td>\n      <td>Sales</td>\n    </tr>\n    <tr>\n      <th>668</th>\n      <td>JE3902</td>\n      <td>2025-06-09</td>\n      <td>Cost of Goods Sold</td>\n      <td>112000.0</td>\n      <td>Operations</td>\n    </tr>\n    <tr>\n      <th>1002</th>\n      <td>JE3903</td>\n      <td>2025-08-30</td>\n      <td>Accounts Receivable</td>\n      <td>176500.0</td>\n      <td>Sales</td>\n    </tr>\n    <tr>\n      <th>1068</th>\n      <td>JE3905</td>\n      <td>2025-09-19</td>\n      <td>Accounts Payable</td>\n      <td>63000.0</td>\n      <td>Operations</td>\n    </tr>\n    <tr>\n      <th>1222</th>\n      <td>JE3904</td>\n      <td>2025-11-02</td>\n      <td>Salaries Expense</td>\n      <td>87000.0</td>\n      <td>HR</td>\n    </tr>\n    <tr>\n      <th>1466</th>\n      <td>JE3906</td>\n      <td>2025-12-24</td>\n      <td>Cash</td>\n      <td>121000.0</td>\n      <td>Sales</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars\n\n::: {#b4aa48fb .cell execution_count=12}\n``` {.python .cell-code}\nmean_val = debit_pl.mean()\nstd_val = debit_pl.std()\n\ngl_with_z = (\n    gl_pl.filter(pl.col(\"debit\") > 0)\n    .with_columns(\n        ((pl.col(\"debit\") - mean_val) / std_val).alias(\"z_score\")\n    )\n)\n\noutliers_z_pl = gl_with_z.filter(pl.col(\"z_score\").abs() > 3)\noutliers_z_pl.select([\"entry_id\", \"entry_date\", \"account\", \"debit\", \"department\"])\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (7, 5)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>entry_id</th><th>entry_date</th><th>account</th><th>debit</th><th>department</th></tr><tr><td>str</td><td>str</td><td>str</td><td>f64</td><td>str</td></tr></thead><tbody><tr><td>&quot;JE3900&quot;</td><td>&quot;2025-03-14&quot;</td><td>&quot;Accounts Receivable&quot;</td><td>145000.0</td><td>&quot;Sales&quot;</td></tr><tr><td>&quot;JE3901&quot;</td><td>&quot;2025-04-22&quot;</td><td>&quot;Cash&quot;</td><td>98000.0</td><td>&quot;Sales&quot;</td></tr><tr><td>&quot;JE3902&quot;</td><td>&quot;2025-06-09&quot;</td><td>&quot;Cost of Goods Sold&quot;</td><td>112000.0</td><td>&quot;Operations&quot;</td></tr><tr><td>&quot;JE3903&quot;</td><td>&quot;2025-08-30&quot;</td><td>&quot;Accounts Receivable&quot;</td><td>176500.0</td><td>&quot;Sales&quot;</td></tr><tr><td>&quot;JE3905&quot;</td><td>&quot;2025-09-19&quot;</td><td>&quot;Accounts Payable&quot;</td><td>63000.0</td><td>&quot;Operations&quot;</td></tr><tr><td>&quot;JE3904&quot;</td><td>&quot;2025-11-02&quot;</td><td>&quot;Salaries Expense&quot;</td><td>87000.0</td><td>&quot;HR&quot;</td></tr><tr><td>&quot;JE3906&quot;</td><td>&quot;2025-12-24&quot;</td><td>&quot;Cash&quot;</td><td>121000.0</td><td>&quot;Sales&quot;</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\nThe z-score method flags exactly **7 transactions** — all well over $60,000, an order of magnitude above the typical transaction size.\n\n### The IQR Method\n\nAn alternative, less sensitive to extreme values than the mean/std-based z-score, uses the interquartile range: flag anything above `Q3 + 1.5 × IQR`.\n\n::: {.panel-tabset}\n## pandas\n\n::: {#74e7b8f2 .cell execution_count=13}\n``` {.python .cell-code}\nupper_bound = q3 + 1.5 * iqr\noutliers_iqr_pd = gl_pd.loc[debit_pd.index][debit_pd > upper_bound]\n\nprint(\"IQR upper bound:\", upper_bound)\nprint(\"Transactions flagged:\", len(outliers_iqr_pd))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIQR upper bound: 7827.0975\nTransactions flagged: 38\n```\n:::\n:::\n\n\n## polars\n\n::: {#2eccf1a4 .cell execution_count=14}\n``` {.python .cell-code}\nupper_bound_pl = q3_pl + 1.5 * iqr_pl\noutliers_iqr_pl = gl_with_z.filter(pl.col(\"debit\") > upper_bound_pl)\n\nprint(\"IQR upper bound:\", upper_bound_pl)\nprint(\"Transactions flagged:\", outliers_iqr_pl.height)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIQR upper bound: 7827.0975\nTransactions flagged: 38\n```\n:::\n:::\n\n\n:::\n\nNotice the IQR method flags **38 transactions** — far more than the 7 flagged by the z-score method. This isn't a bug; it's a real methodological difference:\n\n::: {.callout-important}\n## Z-Score vs. IQR: Why Do They Disagree?\nThe z-score method uses the **mean and standard deviation**, both of which are themselves heavily influenced by extreme values — a few huge transactions inflate the standard deviation, which makes the z-score threshold more forgiving. The IQR method uses the **median and quartiles**, which are far more resistant to extreme values, so it stays \"strict\" even when a few huge outliers are present. In practice, this means:\n\n- The **z-score method** here caught only the most extreme injected anomalies (all above $60,000)\n- The **IQR method** also caught moderately large, but still plausible, legitimate transactions\n\nNeither method is \"correct\" on its own — the IQR method casts a wider net and will produce more false positives requiring manual review, while the z-score method may miss moderately unusual transactions when the data itself is highly skewed. In practice, many audit and fraud analytics workflows use IQR-style thresholds as a first-pass filter specifically *because* it's more sensitive, and treat the resulting list as candidates for follow-up, not confirmed problems.\n:::\n\n### Outlier or Error? A Judgment Call\n\nStatistical flagging is only the first step. Consider the seven z-score outliers above — some questions a real investigation would ask:\n\n- Is a $176,500 sale plausible for this business, or does it look like a data entry error (an extra digit)?\n- Two of the flagged transactions were posted on a weekend — is that normal for this company, or unusual enough to warrant follow-up?\n- Do the posting employees for these entries normally handle transactions of this size?\n\n::: {#a98b6094 .cell execution_count=15}\n``` {.python .cell-code}\ngl_pd[\"entry_date\"] = pd.to_datetime(gl_pd[\"entry_date\"])\noutliers_z_pd_with_day = outliers_z_pd.copy()\noutliers_z_pd_with_day[\"entry_date\"] = pd.to_datetime(outliers_z_pd_with_day[\"entry_date\"])\noutliers_z_pd_with_day[\"day_of_week\"] = outliers_z_pd_with_day[\"entry_date\"].dt.day_name()\noutliers_z_pd_with_day[[\"entry_id\", \"entry_date\", \"day_of_week\", \"account\", \"debit\", \"posted_by\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>entry_id</th>\n      <th>entry_date</th>\n      <th>day_of_week</th>\n      <th>account</th>\n      <th>debit</th>\n      <th>posted_by</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>322</th>\n      <td>JE3900</td>\n      <td>2025-03-14</td>\n      <td>Friday</td>\n      <td>Accounts Receivable</td>\n      <td>145000.0</td>\n      <td>dwilson</td>\n    </tr>\n    <tr>\n      <th>458</th>\n      <td>JE3901</td>\n      <td>2025-04-22</td>\n      <td>Tuesday</td>\n      <td>Cash</td>\n      <td>98000.0</td>\n      <td>ktaylor</td>\n    </tr>\n    <tr>\n      <th>668</th>\n      <td>JE3902</td>\n      <td>2025-06-09</td>\n      <td>Monday</td>\n      <td>Cost of Goods Sold</td>\n      <td>112000.0</td>\n      <td>dwilson</td>\n    </tr>\n    <tr>\n      <th>1002</th>\n      <td>JE3903</td>\n      <td>2025-08-30</td>\n      <td>Saturday</td>\n      <td>Accounts Receivable</td>\n      <td>176500.0</td>\n      <td>dwilson</td>\n    </tr>\n    <tr>\n      <th>1068</th>\n      <td>JE3905</td>\n      <td>2025-09-19</td>\n      <td>Friday</td>\n      <td>Accounts Payable</td>\n      <td>63000.0</td>\n      <td>ktaylor</td>\n    </tr>\n    <tr>\n      <th>1222</th>\n      <td>JE3904</td>\n      <td>2025-11-02</td>\n      <td>Sunday</td>\n      <td>Salaries Expense</td>\n      <td>87000.0</td>\n      <td>dwilson</td>\n    </tr>\n    <tr>\n      <th>1466</th>\n      <td>JE3906</td>\n      <td>2025-12-24</td>\n      <td>Wednesday</td>\n      <td>Cash</td>\n      <td>121000.0</td>\n      <td>mchen</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nTwo of the seven outliers were posted on a **Saturday or Sunday** — worth flagging for follow-up, since unusual timing combined with an unusually large amount is a stronger signal than either one alone. We'll build on exactly this kind of reasoning in Chapter 9 (Fraud Detection and Anomaly Detection).\n\n## Grouped EDA: Comparing Across Categories\n\nSummary statistics computed on the whole dataset can hide differences between groups. Let's compare debit amounts by department.\n\n::: {.panel-tabset}\n## pandas\n\n::: {#b3482371 .cell execution_count=16}\n``` {.python .cell-code}\ngrouped_pd = (\n    gl_pd[gl_pd[\"debit\"] > 0]\n    .groupby(\"department\")[\"debit\"]\n    .agg([\"count\", \"mean\", \"median\", \"std\"])\n)\ngrouped_pd[\"cv\"] = grouped_pd[\"std\"] / grouped_pd[\"mean\"]\ngrouped_pd\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>count</th>\n      <th>mean</th>\n      <th>median</th>\n      <th>std</th>\n      <th>cv</th>\n    </tr>\n    <tr>\n      <th>department</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Finance</th>\n      <td>50</td>\n      <td>668.231200</td>\n      <td>657.435</td>\n      <td>253.988623</td>\n      <td>0.380091</td>\n    </tr>\n    <tr>\n      <th>HR</th>\n      <td>66</td>\n      <td>6953.794091</td>\n      <td>5534.105</td>\n      <td>10128.610229</td>\n      <td>1.456559</td>\n    </tr>\n    <tr>\n      <th>Operations</th>\n      <td>350</td>\n      <td>2608.582057</td>\n      <td>1987.360</td>\n      <td>6825.529984</td>\n      <td>2.616567</td>\n    </tr>\n    <tr>\n      <th>Sales</th>\n      <td>286</td>\n      <td>5719.480035</td>\n      <td>3184.825</td>\n      <td>16080.360228</td>\n      <td>2.811507</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars\n\n::: {#ddc8fbec .cell execution_count=17}\n``` {.python .cell-code}\ngrouped_pl = (\n    gl_pl.filter(pl.col(\"debit\") > 0)\n    .group_by(\"department\")\n    .agg([\n        pl.len().alias(\"count\"),\n        pl.col(\"debit\").mean().alias(\"mean\"),\n        pl.col(\"debit\").median().alias(\"median\"),\n        pl.col(\"debit\").std().alias(\"std\"),\n    ])\n    .with_columns((pl.col(\"std\") / pl.col(\"mean\")).alias(\"cv\"))\n    .sort(\"department\")\n)\ngrouped_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (4, 6)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>department</th><th>count</th><th>mean</th><th>median</th><th>std</th><th>cv</th></tr><tr><td>str</td><td>u32</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>&quot;Finance&quot;</td><td>50</td><td>668.2312</td><td>657.435</td><td>253.988623</td><td>0.380091</td></tr><tr><td>&quot;HR&quot;</td><td>66</td><td>6953.794091</td><td>5534.105</td><td>10128.610229</td><td>1.456559</td></tr><tr><td>&quot;Operations&quot;</td><td>350</td><td>2608.582057</td><td>1987.36</td><td>6825.529984</td><td>2.616567</td></tr><tr><td>&quot;Sales&quot;</td><td>286</td><td>5719.480035</td><td>3184.825</td><td>16080.360228</td><td>2.811507</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\nA few things worth noticing:\n\n- **Finance** has by far the *lowest* variability (small coefficient of variation) — consistent with routine, predictable transactions like depreciation and insurance amortization.\n- **Sales** and **HR** show much higher variability, partly because several of our injected large outliers landed in those departments.\n- **Operations** has the highest transaction *count* by far, reflecting frequent inventory and vendor-payment activity.\n\nThis kind of grouped comparison is often how an unusual pattern first gets noticed — not from a single transaction, but from *one department's numbers looking different from the others* in a way that invites a closer look.\n\n## Putting It Together: A First-Pass EDA Checklist\n\nThe steps in this chapter form a reusable sequence you can apply to *any* new dataset before moving on to deeper analysis:\n\n1. **Check shape and structure** — row/column count, data types (Chapter 3–4 territory)\n2. **Choose appropriate summary statistics** based on each variable's level of measurement\n3. **Compute central tendency and dispersion** — and compare mean vs. median for signs of skew\n4. **Visualize the distribution** — histogram and boxplot, zooming in if outliers dominate the scale\n5. **Flag outliers** — using both z-score and IQR methods, since they disagree in informative ways\n6. **Compare across categories** — group by a relevant categorical variable (department, account, employee) to see if any group stands out\n\nWe applied all six steps to `general_ledger_large.csv` in this chapter. In Chapter 6, we'll build on this foundation with more advanced and polished visualizations; in Chapters 8–9, we'll apply this same EDA mindset directly to audit and fraud analytics tasks.\n\n## Chapter Summary\n\n- EDA means getting to know your data — its center, its spread, its shape, its oddities — before running any formal analysis, audit test, or model.\n- A variable's level of measurement determines which summary statistics are meaningful; this dataset's ratio-level `debit`/`credit` columns support full arithmetic, while nominal columns like `department` only support counting.\n- Mean and median can diverge substantially in skewed financial data — always check both, since the mean alone can be misleading.\n- The coefficient of variation allows fair comparison of variability across accounts or groups on very different scales.\n- Histograms can be distorted by extreme outliers; zooming in (temporarily excluding extreme values) often reveals the true underlying shape.\n- The z-score and IQR methods for outlier detection can disagree substantially — IQR is more sensitive (and produces more false positives) since it's based on the more outlier-resistant median and quartiles, while z-score is based on the more outlier-sensitive mean and standard deviation.\n- A flagged outlier is not automatically an error — determining that requires investigation and accounting judgment, not just a statistical threshold.\n- Grouped EDA (comparing summary statistics across categories) is often how an unusual pattern first becomes visible.\n\n## Discussion Questions\n\n1. Why does the mean of the debit amounts in this chapter's dataset exceed the median? What would it mean if the opposite were true — median greater than mean?\n2. The IQR method flagged 38 transactions, the z-score method only 7. If you were leading an audit team with limited time, which method would you use for an initial screen, and why?\n3. Two of the seven z-score outliers were posted on a weekend. On its own, is a weekend posting evidence of a problem? What additional information would make you more or less concerned?\n\n## Exercises\n\n1. Using `general_ledger_large.csv`, compute the mean, median, and standard deviation of `debit` for just the **Sales** department, and compare it to the whole-dataset statistics computed in this chapter.\n2. Re-run the z-score and IQR outlier detection methods using the `credit` column instead of `debit`. Are the same journal entries flagged? Explain why or why not, given how the dataset is structured.\n3. Produce a histogram of debit amounts grouped by department (four separate histograms, or one overlaid chart) and describe, in a few sentences, how the distributions differ across departments.\n4. Pick one of the seven z-score-flagged outliers. Write a short (100-word) memo describing what additional information you would request before concluding whether it's a legitimate transaction or an error.\n\n",
    "supporting": [
      "05-exploratory-data-analysis_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}