{
  "hash": "320453752c488a05b8ddf08b149a7dac",
  "result": {
    "engine": "jupyter",
    "markdown": "# Introduction to Predictive Modeling\n\n::: {.callout-note}\n## Learning Objectives\nBy the end of this chapter, you should be able to:\n\n- Explain the difference between regression and classification, and identify which fits a given accounting question\n- Split data into training and test sets, and explain why this matters for evaluating a model honestly\n- Fit and interpret a linear regression model for a continuous accounting outcome\n- Fit and interpret a logistic regression model for a binary accounting outcome (financial distress)\n- Evaluate regression models with MAE, RMSE, and R², and classification models with accuracy, precision, recall, F1, and ROC-AUC\n- Recognize the \"accuracy trap\" that arises with imbalanced outcomes, and avoid over-trusting a single metric\n- Perform all of the above using both pandas and polars, and visualize results with both seaborn and plotnine\n:::\n\n## From Descriptive to Predictive Analytics\n\nRecall the four types of analytics from Chapter 1: descriptive, diagnostic, predictive, and prescriptive. Every chapter so far has lived mostly in the first two — summarizing what happened (Chapter 5), and investigating why (Chapters 8-11). This chapter takes the first step into **predictive analytics**: using historical data to estimate an outcome we don't yet know.\n\nWe'll build two models on two different accounting questions:\n\n1. **Regression** — predicting a continuous outcome: how many days will it take to collect a given invoice? (using `sales_transactions.csv` from Chapter 10)\n2. **Classification** — predicting a binary outcome: is this company financially distressed? (using a new dataset, `company_financial_distress.csv`)\n\n::: {.panel-tabset}\n## pandas\n\n::: {#b0751fe1 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\n\nsales_pd = pd.read_csv(\"data/sales_transactions.csv\", parse_dates=[\"invoice_date\", \"ship_date\", \"payment_date\"])\ndistress_pd = pd.read_csv(\"data/company_financial_distress.csv\")\nprint(sales_pd.shape, distress_pd.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(427, 9) (320, 10)\n```\n:::\n:::\n\n\n## polars \n\n::: {#0ed9321a .cell execution_count=2}\n``` {.python .cell-code}\nimport polars as pl\n\nsales_pl = pl.read_csv(\"data/sales_transactions.csv\", try_parse_dates=True)\ndistress_pl = pl.read_csv(\"data/company_financial_distress.csv\")\nprint(sales_pl.shape, distress_pl.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(427, 9) (320, 10)\n```\n:::\n:::\n\n\n:::\n## Regression: Predicting Days to Collect\n\n### Feature Engineering\n\n::: {.panel-tabset}\n## pandas\n\n::: {#ba52479c .cell execution_count=3}\n``` {.python .cell-code}\npaid_pd = sales_pd[sales_pd[\"is_paid\"]].copy()\npaid_pd[\"days_to_collect\"] = (paid_pd[\"payment_date\"] - paid_pd[\"invoice_date\"]).dt.days\npaid_pd[\"ship_lag_days\"] = (paid_pd[\"ship_date\"] - paid_pd[\"invoice_date\"]).dt.days\npaid_pd[\"log_amount\"] = np.log1p(paid_pd[\"amount\"])\n\npaid_pd[[\"amount\", \"payment_terms_days\", \"quarter\", \"ship_lag_days\", \"days_to_collect\"]].describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=111}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>amount</th>\n      <th>payment_terms_days</th>\n      <th>quarter</th>\n      <th>ship_lag_days</th>\n      <th>days_to_collect</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>360.000000</td>\n      <td>360.000000</td>\n      <td>360.000000</td>\n      <td>360.000000</td>\n      <td>360.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>5014.964194</td>\n      <td>47.791667</td>\n      <td>2.250000</td>\n      <td>-0.822222</td>\n      <td>51.338889</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>5143.852818</td>\n      <td>11.809700</td>\n      <td>1.028155</td>\n      <td>2.543560</td>\n      <td>36.141653</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>841.050000</td>\n      <td>30.000000</td>\n      <td>1.000000</td>\n      <td>-2.000000</td>\n      <td>5.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>2426.720000</td>\n      <td>45.000000</td>\n      <td>1.000000</td>\n      <td>-2.000000</td>\n      <td>27.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>3892.305000</td>\n      <td>45.000000</td>\n      <td>2.000000</td>\n      <td>-1.000000</td>\n      <td>41.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>6102.247500</td>\n      <td>60.000000</td>\n      <td>3.000000</td>\n      <td>0.000000</td>\n      <td>61.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>62000.000000</td>\n      <td>60.000000</td>\n      <td>4.000000</td>\n      <td>30.000000</td>\n      <td>209.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars\n\n::: {#b20cdadb .cell execution_count=4}\n``` {.python .cell-code}\npaid_pl = sales_pl.filter(pl.col(\"is_paid\")).with_columns([\n    (pl.col(\"payment_date\") - pl.col(\"invoice_date\")).dt.total_days().alias(\"days_to_collect\"),\n    (pl.col(\"ship_date\") - pl.col(\"invoice_date\")).dt.total_days().alias(\"ship_lag_days\"),\n    pl.col(\"amount\").log1p().alias(\"log_amount\"),\n])\n\npaid_pl.select([\"amount\", \"payment_terms_days\", \"quarter\", \"ship_lag_days\", \"days_to_collect\"]).describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=112}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (9, 6)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>statistic</th><th>amount</th><th>payment_terms_days</th><th>quarter</th><th>ship_lag_days</th><th>days_to_collect</th></tr><tr><td>str</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>&quot;count&quot;</td><td>360.0</td><td>360.0</td><td>360.0</td><td>360.0</td><td>360.0</td></tr><tr><td>&quot;null_count&quot;</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td><td>0.0</td></tr><tr><td>&quot;mean&quot;</td><td>5014.964194</td><td>47.791667</td><td>2.25</td><td>-0.822222</td><td>51.338889</td></tr><tr><td>&quot;std&quot;</td><td>5143.852818</td><td>11.8097</td><td>1.028155</td><td>2.54356</td><td>36.141653</td></tr><tr><td>&quot;min&quot;</td><td>841.05</td><td>30.0</td><td>1.0</td><td>-2.0</td><td>5.0</td></tr><tr><td>&quot;25%&quot;</td><td>2429.3</td><td>45.0</td><td>1.0</td><td>-2.0</td><td>27.0</td></tr><tr><td>&quot;50%&quot;</td><td>3931.69</td><td>45.0</td><td>2.0</td><td>-1.0</td><td>41.0</td></tr><tr><td>&quot;75%&quot;</td><td>6079.72</td><td>60.0</td><td>3.0</td><td>0.0</td><td>61.0</td></tr><tr><td>&quot;max&quot;</td><td>62000.0</td><td>60.0</td><td>4.0</td><td>30.0</td><td>209.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\n::: {.callout-tip}\n## Connect to Practice\nRecall from Chapter 10 that restricting to *paid* invoices introduces survivorship bias when comparing DSO across recent periods. The same caution applies here: this model is trained only on invoices that have already been collected, which may not perfectly represent the invoices still outstanding. Keep this in mind when interpreting the model's real-world usefulness later in this chapter.\n:::\n\n### Train/Test Split\n\nBefore fitting any model, we set aside a portion of the data the model never sees during training, so we can honestly evaluate how well it generalizes to new invoices.\n\n::: {#c2250f29 .cell execution_count=5}\n``` {.python .cell-code}\nfrom sklearn.model_selection import train_test_split\n\nfeatures_reg = [\"log_amount\", \"payment_terms_days\", \"quarter\", \"ship_lag_days\"]\nX = paid_pd[features_reg]\ny = paid_pd[\"days_to_collect\"]\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)\nprint(f\"Training set: {len(X_train)} invoices, Test set: {len(X_test)} invoices\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTraining set: 270 invoices, Test set: 90 invoices\n```\n:::\n:::\n\n\n::: {.callout-important}\n## Why Not Just Use All the Data?\nIf we fit a model on all 360 invoices and evaluated it on those same 360 invoices, we'd be measuring how well the model *memorized* this specific data, not how well it will perform on the next new invoice. Setting aside a test set the model never sees during training is the standard way to get an honest estimate of real-world performance.\n:::\n\n### Fitting and Interpreting the Model\n\n:::{.panel-tabset}\n## scikit-learn\n\n::: {#20535614 .cell execution_count=6}\n``` {.python .cell-code}\nfrom sklearn.linear_model import LinearRegression\n\nreg_model = LinearRegression()\nreg_model.fit(X_train, y_train)\n\nfor feature, coef in zip(features_reg, reg_model.coef_):\n    print(f\"{feature}: {coef:.3f}\")\nprint(f\"Intercept: {reg_model.intercept_:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlog_amount: -3.263\npayment_terms_days: 0.971\nquarter: -6.214\nship_lag_days: 0.135\nIntercept: 44.940\n```\n:::\n:::\n\n\n## pyfixest \n\n::: {#c82b9292 .cell execution_count=7}\n``` {.python .cell-code}\nimport pyfixest as pf\nfrom pyfixest.estimation import feols\n\nmodel = feols(\"days_to_collect ~ log_amount + payment_terms_days +  quarter + ship_lag_days\", data = paid_pd)\n\npf.etable([model])\n```\n\n::: {.cell-output .cell-output-display execution_count=115}\n```{=html}\n<div id=\"nolhwcfqgv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#nolhwcfqgv table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#nolhwcfqgv thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#nolhwcfqgv p { margin: 0; padding: 0; }\n #nolhwcfqgv .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 16px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: hidden; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #nolhwcfqgv .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #nolhwcfqgv .gt_title { color: #333333; font-size: 16px; font-weight: initial; padding-top: 6px; padding-bottom: 6px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }\n #nolhwcfqgv .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 5px; padding-bottom: 7px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }\n #nolhwcfqgv .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #nolhwcfqgv .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #nolhwcfqgv .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: black; border-bottom-style: solid; border-bottom-width: 0.25px; border-bottom-color: black; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #nolhwcfqgv .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 16px; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 0px; border-left-color: white; border-right-style: none; border-right-width: 0px; border-right-color: white; vertical-align: bottom; padding-top: 2px; padding-bottom: 7px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #nolhwcfqgv .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 16px; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #nolhwcfqgv .gt_column_spanner_outer:first-child { padding-left: 0; }\n #nolhwcfqgv .gt_column_spanner_outer:last-child { padding-right: 0; }\n #nolhwcfqgv .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 0.25px; border-bottom-color: black; vertical-align: bottom; padding-top: 2px; padding-bottom: 2px; overflow-x: hidden; display: inline-block; width: 100%; }\n #nolhwcfqgv .gt_spanner_row { border-bottom-style: hidden; }\n #nolhwcfqgv .gt_group_heading { padding-top: 0px; padding-bottom: 0px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 0px; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 0.25px; border-top-color: black; border-bottom-style: solid; border-bottom-width: 0.25px; border-bottom-color: black; border-left-style: none; border-left-width: 1px; border-left-color: white; border-right-style: none; border-right-width: 1px; border-right-color: white; vertical-align: middle; text-align: left; }\n #nolhwcfqgv .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 0px; font-weight: initial; border-top-style: solid; border-top-width: 0.25px; border-top-color: black; border-bottom-style: solid; border-bottom-width: 0.25px; border-bottom-color: black; vertical-align: middle; }\n #nolhwcfqgv .gt_from_md> :first-child { margin-top: 0; }\n #nolhwcfqgv .gt_from_md> :last-child { margin-bottom: 0; }\n #nolhwcfqgv .gt_row { padding-top: 2px; padding-bottom: 2px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: none; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 0px; border-left-color: white; border-right-style: none; border-right-width: 0px; border-right-color: white; vertical-align: middle; overflow-x: hidden; }\n #nolhwcfqgv .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 16px; font-weight: initial; text-transform: inherit; border-right-style: hidden; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #nolhwcfqgv .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #nolhwcfqgv .gt_row_group_first td { border-top-width: 0.25px; }\n #nolhwcfqgv .gt_row_group_first th { border-top-width: 0.25px; }\n #nolhwcfqgv .gt_striped { color: #333333; background-color: #F4F4F4; }\n #nolhwcfqgv .gt_table_body { border-top-style: solid; border-top-width: 0px; border-top-color: black; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: black; }\n #nolhwcfqgv .gt_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #nolhwcfqgv .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #nolhwcfqgv .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #nolhwcfqgv .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #nolhwcfqgv .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #nolhwcfqgv .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #nolhwcfqgv .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #nolhwcfqgv .gt_sourcenote { font-size: 10px; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #nolhwcfqgv .gt_left { text-align: left; }\n #nolhwcfqgv .gt_center { text-align: center; }\n #nolhwcfqgv .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #nolhwcfqgv .gt_font_normal { font-weight: normal; }\n #nolhwcfqgv .gt_font_bold { font-weight: bold; }\n #nolhwcfqgv .gt_font_italic { font-style: italic; }\n #nolhwcfqgv .gt_super { font-size: 65%; }\n #nolhwcfqgv .gt_footnotes { color: font-color(#FFFFFF); background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #nolhwcfqgv .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #nolhwcfqgv .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #nolhwcfqgv .gt_sourcenote { font-size: 10px; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #nolhwcfqgv .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #nolhwcfqgv .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n<tr class=\"gt_col_headings gt_spanner_row\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"\"></th>\n  <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"days_to_collect\">\n    <span class=\"gt_column_spanner\">days_to_collect</span>\n  </th>\n</tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"0\">(1)</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr class=\"gt_group_heading_row\">\n    <th class=\"gt_group_heading\" colspan=\"2\">coef</th>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">log_amount</th>\n    <td class=\"gt_row gt_center\">-4.814 <br> (2.840)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">payment_terms_days</th>\n    <td class=\"gt_row gt_center\">0.903*** <br> (0.152)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">quarter</th>\n    <td class=\"gt_row gt_center\">-7.059*** <br> (1.740)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">ship_lag_days</th>\n    <td class=\"gt_row gt_center\">0.220 <br> (0.734)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">Intercept</th>\n    <td class=\"gt_row gt_center\">64.088* <br> (25.452)</td>\n  </tr>\n  <tr class=\"gt_group_heading_row\">\n    <th class=\"gt_group_heading\" colspan=\"2\">stats</th>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">Observations</th>\n    <td class=\"gt_row gt_center\">360</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">R<sup>2</sup></th>\n    <td class=\"gt_row gt_center\">0.158</td>\n  </tr>\n</tbody>\n<tfoot><tr class=\"gt_sourcenotes\"><td class=\"gt_sourcenote\" colspan=\"2\"><span class=\"gt_from_md\">Significance levels: * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001. Format of coefficient cell: Coefficient   (Std. Error)</span></td></tr></tfoot>\n</table>\n\n</div>\n```\n:::\n:::\n\n\n::: {#66ea5a4e .cell execution_count=8}\n``` {.python .cell-code}\nmodel.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  OLS\nDep. var.: days_to_collect\nsample: None = all\nInference:  iid\nObservations:  360\n\n| Coefficient        |   Estimate |   Std. Error |   t value |   Pr(>|t|) |    2.5% |   97.5% |\n|:-------------------|-----------:|-------------:|----------:|-----------:|--------:|--------:|\n| Intercept          |     64.088 |       25.452 |     2.518 |      0.012 |  14.031 | 114.144 |\n| log_amount         |     -4.814 |        2.840 |    -1.695 |      0.091 | -10.399 |   0.772 |\n| payment_terms_days |      0.903 |        0.152 |     5.957 |      0.000 |   0.605 |   1.201 |\n| quarter            |     -7.059 |        1.740 |    -4.057 |      0.000 | -10.480 |  -3.637 |\n| ship_lag_days      |      0.220 |        0.734 |     0.300 |      0.764 |  -1.223 |   1.663 |\n---\nRMSE: 33.116 R2: 0.158 \n```\n:::\n:::\n\n\n::: {#8bdc8c63 .cell execution_count=9}\n``` {.python .cell-code}\npf.summary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  OLS\nDep. var.: days_to_collect\nsample: None = all\nInference:  iid\nObservations:  360\n\n| Coefficient        |   Estimate |   Std. Error |   t value |   Pr(>|t|) |    2.5% |   97.5% |\n|:-------------------|-----------:|-------------:|----------:|-----------:|--------:|--------:|\n| Intercept          |     64.088 |       25.452 |     2.518 |      0.012 |  14.031 | 114.144 |\n| log_amount         |     -4.814 |        2.840 |    -1.695 |      0.091 | -10.399 |   0.772 |\n| payment_terms_days |      0.903 |        0.152 |     5.957 |      0.000 |   0.605 |   1.201 |\n| quarter            |     -7.059 |        1.740 |    -4.057 |      0.000 | -10.480 |  -3.637 |\n| ship_lag_days      |      0.220 |        0.734 |     0.300 |      0.764 |  -1.223 |   1.663 |\n---\nRMSE: 33.116 R2: 0.158 \n```\n:::\n:::\n\n\n::: {#364c2da4 .cell execution_count=10}\n``` {.python .cell-code}\nmodel.tidy()\n```\n\n::: {.cell-output .cell-output-display execution_count=118}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Estimate</th>\n      <th>Std. Error</th>\n      <th>t value</th>\n      <th>Pr(&gt;|t|)</th>\n      <th>2.5%</th>\n      <th>97.5%</th>\n    </tr>\n    <tr>\n      <th>Coefficient</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>64.087655</td>\n      <td>25.452490</td>\n      <td>2.517933</td>\n      <td>1.224390e-02</td>\n      <td>14.031034</td>\n      <td>114.144276</td>\n    </tr>\n    <tr>\n      <th>log_amount</th>\n      <td>-4.813551</td>\n      <td>2.840305</td>\n      <td>-1.694730</td>\n      <td>9.100358e-02</td>\n      <td>-10.399491</td>\n      <td>0.772389</td>\n    </tr>\n    <tr>\n      <th>payment_terms_days</th>\n      <td>0.902613</td>\n      <td>0.151513</td>\n      <td>5.957333</td>\n      <td>6.175350e-09</td>\n      <td>0.604638</td>\n      <td>1.200589</td>\n    </tr>\n    <tr>\n      <th>quarter</th>\n      <td>-7.058792</td>\n      <td>1.739809</td>\n      <td>-4.057223</td>\n      <td>6.109975e-05</td>\n      <td>-10.480419</td>\n      <td>-3.637164</td>\n    </tr>\n    <tr>\n      <th>ship_lag_days</th>\n      <td>0.220201</td>\n      <td>0.733691</td>\n      <td>0.300128</td>\n      <td>7.642549e-01</td>\n      <td>-1.222725</td>\n      <td>1.663128</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#da3b8fce .cell execution_count=11}\n``` {.python .cell-code}\nmodel.coef()\nmodel.se()\nmodel.tstat()\nmodel.confint()\n```\n\n::: {.cell-output .cell-output-display execution_count=119}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>2.5%</th>\n      <th>97.5%</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>14.031034</td>\n      <td>114.144276</td>\n    </tr>\n    <tr>\n      <th>log_amount</th>\n      <td>-10.399491</td>\n      <td>0.772389</td>\n    </tr>\n    <tr>\n      <th>payment_terms_days</th>\n      <td>0.604638</td>\n      <td>1.200589</td>\n    </tr>\n    <tr>\n      <th>quarter</th>\n      <td>-10.480419</td>\n      <td>-3.637164</td>\n    </tr>\n    <tr>\n      <th>ship_lag_days</th>\n      <td>-1.222725</td>\n      <td>1.663128</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-DTC .cell execution_count=12}\n``` {.python .cell-code}\nmodel.coefplot()\n# or pf.coefplot(model)\n```\n\n::: {.cell-output .cell-output-display execution_count=120}\n![Factors Affecting Days to Collect (DTC)](12-predictive-modeling-intro_files/figure-html/fig-dtc-output-1.png){#fig-dtc width=956 height=566}\n:::\n:::\n\n\n:::\n\n\nA few coefficients are worth reading carefully:\n\n- **`payment_terms_days` (+0.97)**: each additional day of payment terms offered is associated with almost exactly one additional day to collect — customers largely pay according to the terms they're given, which is reassuring and expected.\n- **`quarter` (-6.2)**: later quarters are associated with *faster* collection. This should look familiar — it's the same declining-DSO pattern from Chapter 10, which we already know is partly a survivorship bias artifact from measuring near a fixed cutoff date, not necessarily a genuine operational improvement.\n- **`log_amount` (-3.3)**: larger invoices tend to be collected slightly faster, plausibly because larger balances get more collections attention.\n\n@fig-DTC presents the importance of coefficients.\n\n### Evaluating the Model\n\n::: {#6cecc493 .cell execution_count=13}\n``` {.python .cell-code}\nfrom sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n\ny_pred = reg_model.predict(X_test)\n\nmae = mean_absolute_error(y_test, y_pred)\nrmse = np.sqrt(mean_squared_error(y_test, y_pred))\nr2 = r2_score(y_test, y_pred)\n\nprint(f\"MAE:  {mae:.1f} days\")\nprint(f\"RMSE: {rmse:.1f} days\")\nprint(f\"R²:   {r2:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMAE:  23.7 days\nRMSE: 34.8 days\nR²:   0.141\n```\n:::\n:::\n\n\n::: {#74adc7e1 .cell execution_count=14}\n``` {.python .cell-code}\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\npred_df = pd.DataFrame({\"actual\": y_test, \"predicted\": y_pred})\n```\n:::\n\n\n::: {.panel-tabset}\n## seaborn\n\n::: {#46a67b69 .cell execution_count=15}\n``` {.python .cell-code}\nplt.figure(figsize=(6, 5))\nsns.scatterplot(data=pred_df, x=\"actual\", y=\"predicted\", alpha=0.6, color=\"#1c7c73\")\nlims = [0, max(pred_df[\"actual\"].max(), pred_df[\"predicted\"].max())]\nplt.plot(lims, lims, \"--\", color=\"gray\")\nplt.title(\"Predicted vs. Actual Days to Collect\")\nplt.xlabel(\"Actual Days to Collect\")\nplt.ylabel(\"Predicted Days to Collect\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](12-predictive-modeling-intro_files/figure-html/cell-16-output-1.png){width=567 height=470}\n:::\n:::\n\n\n## plotnine\n\n::: {#b52955d4 .cell execution_count=16}\n``` {.python .cell-code}\nfrom plotnine import *\n\n(\n    ggplot(pred_df, aes(x=\"actual\", y=\"predicted\"))\n    + geom_point(alpha=0.6, color=\"#1c7c73\")\n    + geom_abline(slope=1, intercept=0, linetype=\"dashed\", color=\"gray\")\n    + labs(title=\"Predicted vs. Actual Days to Collect\", x=\"Actual Days to Collect\", y=\"Predicted Days to Collect\")\n    + theme_minimal()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=124}\n![](12-predictive-modeling-intro_files/figure-html/cell-17-output-1.png){width=672 height=480}\n:::\n:::\n\n\n:::\n\n::: {.callout-important}\n## An Honest Look at a Weak Model\nAn R² of roughly 0.14 means this model explains only about **14% of the variation** in how long invoices take to collect — the rest is essentially unmodeled from these four features alone. The scatter plot makes this concrete: predictions cluster in a fairly narrow band regardless of the actual outcome, which swings far more widely. This is a realistic and important result, not a failure of the chapter. **Not every accounting prediction problem yields a strong model**, and reporting a weak R² honestly is far more useful than cherry-picking features until a chart looks better. Collection timing likely depends on factors we haven't captured here at all — a specific customer's cash position, an ongoing dispute, or a change in the customer's own collections priorities.\n:::\n\n## Classification: Predicting Financial Distress\n\nOur second dataset, `company_financial_distress.csv`, contains financial ratios for 320 companies along with a binary outcome: whether each company experienced **financial distress** in the following year. The ratios mirror those used in classic bankruptcy prediction research (e.g., the Altman Z-score): liquidity, leverage, profitability, and efficiency measures.\n\n::: {#5ecad198 .cell execution_count=17}\n``` {.python .cell-code}\ndistress_pd.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=125}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>company_id</th>\n      <th>current_ratio</th>\n      <th>debt_to_equity</th>\n      <th>roa</th>\n      <th>net_margin</th>\n      <th>asset_turnover</th>\n      <th>interest_coverage</th>\n      <th>working_capital_to_assets</th>\n      <th>retained_earnings_to_assets</th>\n      <th>financial_distress</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>CO1000</td>\n      <td>3.07</td>\n      <td>0.29</td>\n      <td>0.1017</td>\n      <td>0.1413</td>\n      <td>1.15</td>\n      <td>8.65</td>\n      <td>0.142</td>\n      <td>-0.129</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>CO1001</td>\n      <td>1.29</td>\n      <td>0.72</td>\n      <td>-0.1067</td>\n      <td>0.0564</td>\n      <td>0.20</td>\n      <td>14.20</td>\n      <td>0.148</td>\n      <td>0.429</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>CO1002</td>\n      <td>1.04</td>\n      <td>0.65</td>\n      <td>0.1469</td>\n      <td>-0.1050</td>\n      <td>2.17</td>\n      <td>-1.08</td>\n      <td>0.093</td>\n      <td>0.700</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>CO1003</td>\n      <td>1.52</td>\n      <td>0.89</td>\n      <td>-0.0288</td>\n      <td>0.0602</td>\n      <td>1.36</td>\n      <td>5.83</td>\n      <td>0.147</td>\n      <td>0.224</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>CO1004</td>\n      <td>0.99</td>\n      <td>0.70</td>\n      <td>-0.1236</td>\n      <td>-0.1677</td>\n      <td>1.29</td>\n      <td>7.05</td>\n      <td>0.236</td>\n      <td>0.175</td>\n      <td>1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#a6a23a4b .cell execution_count=18}\n``` {.python .cell-code}\nprint(\"Distress rate:\", distress_pd[\"financial_distress\"].mean().round(3))\ndistress_pd[\"financial_distress\"].value_counts()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDistress rate: 0.169\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=126}\n```\nfinancial_distress\n0    266\n1     54\nName: count, dtype: int64\n```\n:::\n:::\n\n\nOnly about 17% of companies in this dataset are labeled distressed — an imbalance worth keeping in mind, since it will matter a great deal when we evaluate the model shortly.\n\n### Comparing Distressed vs. Healthy Companies\n\n::: {.panel-tabset}\n## pandas\n\n::: {#a7433284 .cell execution_count=19}\n``` {.python .cell-code}\ndistress_pd.groupby(\"financial_distress\")[\n    [\"current_ratio\", \"debt_to_equity\", \"roa\", \"interest_coverage\"]\n].mean().round(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=127}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>current_ratio</th>\n      <th>debt_to_equity</th>\n      <th>roa</th>\n      <th>interest_coverage</th>\n    </tr>\n    <tr>\n      <th>financial_distress</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1.845</td>\n      <td>0.857</td>\n      <td>0.063</td>\n      <td>6.614</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1.538</td>\n      <td>1.354</td>\n      <td>0.019</td>\n      <td>5.231</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars\n\n::: {#cd9f67bf .cell execution_count=20}\n``` {.python .cell-code}\ndistress_pl.group_by(\"financial_distress\").agg([\n    pl.col(\"current_ratio\").mean(),\n    pl.col(\"debt_to_equity\").mean(),\n    pl.col(\"roa\").mean(),\n    pl.col(\"interest_coverage\").mean(),\n]).sort(\"financial_distress\")\n```\n\n::: {.cell-output .cell-output-display execution_count=128}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (2, 5)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>financial_distress</th><th>current_ratio</th><th>debt_to_equity</th><th>roa</th><th>interest_coverage</th></tr><tr><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>0</td><td>1.845489</td><td>0.856729</td><td>0.062801</td><td>6.614211</td></tr><tr><td>1</td><td>1.537593</td><td>1.353704</td><td>0.018669</td><td>5.231296</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\nThe direction of every difference matches financial theory: distressed companies show a lower current ratio (less liquidity), higher debt-to-equity (more leverage), lower ROA (less profitable), and lower interest coverage (less cushion to service debt).\n\n### Train/Test Split and Standardization\n\n::: {#d8961436 .cell execution_count=21}\n``` {.python .cell-code}\nfeatures_clf = [\n    \"current_ratio\", \"debt_to_equity\", \"roa\", \"net_margin\",\n    \"asset_turnover\", \"interest_coverage\", \"working_capital_to_assets\", \"retained_earnings_to_assets\",\n]\n\nXc = distress_pd[features_clf]\nyc = distress_pd[\"financial_distress\"]\n\nXc_train, Xc_test, yc_train, yc_test = train_test_split(\n    Xc, yc, test_size=0.25, random_state=42, stratify=yc\n)\nprint(\"Train distress rate:\", yc_train.mean().round(3), \" Test distress rate:\", yc_test.mean().round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrain distress rate: 0.171  Test distress rate: 0.162\n```\n:::\n:::\n\n\nNotice `stratify=yc` — this ensures the train and test sets both preserve the same 17% distress rate, rather than risking a split where, by chance, the test set ends up with very few (or zero) distressed companies.\n\n::: {#073d7e94 .cell execution_count=22}\n``` {.python .cell-code}\nfrom sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\nXc_train_scaled = scaler.fit_transform(Xc_train)\nXc_test_scaled = scaler.transform(Xc_test)\n```\n:::\n\n\n::: {.callout-tip}\n## Why Standardize for Logistic Regression?\nOur features span very different scales — `debt_to_equity` typically ranges from 0 to 4, while `interest_coverage` ranges from -5 to 30. Standardizing (subtracting the mean, dividing by the standard deviation) puts every feature on a comparable scale, which makes the resulting coefficients directly comparable to each other — a larger coefficient genuinely means a stronger effect, not just a feature with bigger raw numbers.\n:::\n\n### Fitting the Model\n\n:::{.panel-tabset}\n## scikit-learn\n\n::: {#348dd242 .cell execution_count=23}\n``` {.python .cell-code}\nfrom sklearn.linear_model import LogisticRegression\n\nclf_model = LogisticRegression(random_state=42)\nclf_model.fit(Xc_train_scaled, yc_train)\n\ncoef_df = pd.DataFrame({\"feature\": features_clf, \"coefficient\": clf_model.coef_[0]}).sort_values(\"coefficient\")\ncoef_df[\"direction\"] = coef_df[\"coefficient\"].apply(lambda c: \"Increases Risk\" if c > 0 else \"Decreases Risk\")\ncoef_df\n```\n\n::: {.cell-output .cell-output-display execution_count=131}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>feature</th>\n      <th>coefficient</th>\n      <th>direction</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>current_ratio</td>\n      <td>-0.738514</td>\n      <td>Decreases Risk</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>roa</td>\n      <td>-0.656879</td>\n      <td>Decreases Risk</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>net_margin</td>\n      <td>-0.614102</td>\n      <td>Decreases Risk</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>retained_earnings_to_assets</td>\n      <td>-0.376256</td>\n      <td>Decreases Risk</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>interest_coverage</td>\n      <td>-0.300631</td>\n      <td>Decreases Risk</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>working_capital_to_assets</td>\n      <td>-0.179103</td>\n      <td>Decreases Risk</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>asset_turnover</td>\n      <td>0.011675</td>\n      <td>Increases Risk</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>debt_to_equity</td>\n      <td>1.206548</td>\n      <td>Increases Risk</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## pyfixest \n\n::: {#00f1846f .cell execution_count=24}\n``` {.python .cell-code}\nmodel_2 = pf.feglm(\"financial_distress ~ current_ratio +  debt_to_equity + roa + net_margin + asset_turnover + interest_coverage +  working_capital_to_assets +  retained_earnings_to_assets\", data = distress_pd, family = \"logit\")\n\npf.etable([model_2])\n```\n\n::: {.cell-output .cell-output-display execution_count=132}\n```{=html}\n<div id=\"vdyigjwpgp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#vdyigjwpgp table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#vdyigjwpgp thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#vdyigjwpgp p { margin: 0; padding: 0; }\n #vdyigjwpgp .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 16px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: hidden; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #vdyigjwpgp .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #vdyigjwpgp .gt_title { color: #333333; font-size: 16px; font-weight: initial; padding-top: 6px; padding-bottom: 6px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }\n #vdyigjwpgp .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 5px; padding-bottom: 7px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }\n #vdyigjwpgp .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #vdyigjwpgp .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #vdyigjwpgp .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: black; border-bottom-style: solid; border-bottom-width: 0.25px; border-bottom-color: black; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #vdyigjwpgp .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 16px; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 0px; border-left-color: white; border-right-style: none; border-right-width: 0px; border-right-color: white; vertical-align: bottom; padding-top: 2px; padding-bottom: 7px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #vdyigjwpgp .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 16px; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #vdyigjwpgp .gt_column_spanner_outer:first-child { padding-left: 0; }\n #vdyigjwpgp .gt_column_spanner_outer:last-child { padding-right: 0; }\n #vdyigjwpgp .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 0.25px; border-bottom-color: black; vertical-align: bottom; padding-top: 2px; padding-bottom: 2px; overflow-x: hidden; display: inline-block; width: 100%; }\n #vdyigjwpgp .gt_spanner_row { border-bottom-style: hidden; }\n #vdyigjwpgp .gt_group_heading { padding-top: 0px; padding-bottom: 0px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 0px; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 0.25px; border-top-color: black; border-bottom-style: solid; border-bottom-width: 0.25px; border-bottom-color: black; border-left-style: none; border-left-width: 1px; border-left-color: white; border-right-style: none; border-right-width: 1px; border-right-color: white; vertical-align: middle; text-align: left; }\n #vdyigjwpgp .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 0px; font-weight: initial; border-top-style: solid; border-top-width: 0.25px; border-top-color: black; border-bottom-style: solid; border-bottom-width: 0.25px; border-bottom-color: black; vertical-align: middle; }\n #vdyigjwpgp .gt_from_md> :first-child { margin-top: 0; }\n #vdyigjwpgp .gt_from_md> :last-child { margin-bottom: 0; }\n #vdyigjwpgp .gt_row { padding-top: 2px; padding-bottom: 2px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: none; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 0px; border-left-color: white; border-right-style: none; border-right-width: 0px; border-right-color: white; vertical-align: middle; overflow-x: hidden; }\n #vdyigjwpgp .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 16px; font-weight: initial; text-transform: inherit; border-right-style: hidden; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #vdyigjwpgp .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #vdyigjwpgp .gt_row_group_first td { border-top-width: 0.25px; }\n #vdyigjwpgp .gt_row_group_first th { border-top-width: 0.25px; }\n #vdyigjwpgp .gt_striped { color: #333333; background-color: #F4F4F4; }\n #vdyigjwpgp .gt_table_body { border-top-style: solid; border-top-width: 0px; border-top-color: black; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: black; }\n #vdyigjwpgp .gt_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #vdyigjwpgp .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #vdyigjwpgp .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #vdyigjwpgp .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #vdyigjwpgp .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #vdyigjwpgp .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #vdyigjwpgp .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #vdyigjwpgp .gt_sourcenote { font-size: 10px; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #vdyigjwpgp .gt_left { text-align: left; }\n #vdyigjwpgp .gt_center { text-align: center; }\n #vdyigjwpgp .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #vdyigjwpgp .gt_font_normal { font-weight: normal; }\n #vdyigjwpgp .gt_font_bold { font-weight: bold; }\n #vdyigjwpgp .gt_font_italic { font-style: italic; }\n #vdyigjwpgp .gt_super { font-size: 65%; }\n #vdyigjwpgp .gt_footnotes { color: font-color(#FFFFFF); background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #vdyigjwpgp .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #vdyigjwpgp .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #vdyigjwpgp .gt_sourcenote { font-size: 10px; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #vdyigjwpgp .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #vdyigjwpgp .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n<tr class=\"gt_col_headings gt_spanner_row\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"\"></th>\n  <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"financial_distress\">\n    <span class=\"gt_column_spanner\">financial_distress</span>\n  </th>\n</tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"0\">(1)</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr class=\"gt_group_heading_row\">\n    <th class=\"gt_group_heading\" colspan=\"2\">coef</th>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">current_ratio</th>\n    <td class=\"gt_row gt_center\">-0.885*** <br> (0.258)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">debt_to_equity</th>\n    <td class=\"gt_row gt_center\">2.100*** <br> (0.365)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">roa</th>\n    <td class=\"gt_row gt_center\">-9.956*** <br> (2.487)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">net_margin</th>\n    <td class=\"gt_row gt_center\">-8.285*** <br> (2.217)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">asset_turnover</th>\n    <td class=\"gt_row gt_center\">0.017 <br> (0.497)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">interest_coverage</th>\n    <td class=\"gt_row gt_center\">-0.086* <br> (0.042)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">working_capital_to_assets</th>\n    <td class=\"gt_row gt_center\">-2.079 <br> (1.247)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">retained_earnings_to_assets</th>\n    <td class=\"gt_row gt_center\">-2.011* <br> (0.958)</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">Intercept</th>\n    <td class=\"gt_row gt_center\">-0.567 <br> (0.851)</td>\n  </tr>\n  <tr class=\"gt_group_heading_row\">\n    <th class=\"gt_group_heading\" colspan=\"2\">stats</th>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">Observations</th>\n    <td class=\"gt_row gt_center\">320</td>\n  </tr>\n  <tr>\n    <th class=\"gt_row gt_left gt_stub\">R<sup>2</sup></th>\n    <td class=\"gt_row gt_center\">-</td>\n  </tr>\n</tbody>\n<tfoot><tr class=\"gt_sourcenotes\"><td class=\"gt_sourcenote\" colspan=\"2\"><span class=\"gt_from_md\">Significance levels: * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001. Format of coefficient cell: Coefficient   (Std. Error)</span></td></tr></tfoot>\n</table>\n\n</div>\n```\n:::\n:::\n\n\n::: {#b8f65390 .cell execution_count=25}\n``` {.python .cell-code}\npf.summary(model_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  Logit\nDep. var.: financial_distress\nsample: None = all\nInference:  iid\nObservations:  320\n\n| Coefficient                 |   Estimate |   Std. Error |   t value |   Pr(>|t|) |    2.5% |   97.5% |\n|:----------------------------|-----------:|-------------:|----------:|-----------:|--------:|--------:|\n| Intercept                   |     -0.567 |        0.851 |    -0.666 |      0.505 |  -2.235 |   1.101 |\n| current_ratio               |     -0.885 |        0.258 |    -3.426 |      0.001 |  -1.392 |  -0.379 |\n| debt_to_equity              |      2.100 |        0.365 |     5.761 |      0.000 |   1.386 |   2.815 |\n| roa                         |     -9.956 |        2.487 |    -4.002 |      0.000 | -14.831 |  -5.080 |\n| net_margin                  |     -8.285 |        2.217 |    -3.737 |      0.000 | -12.631 |  -3.940 |\n| asset_turnover              |      0.017 |        0.497 |     0.035 |      0.972 |  -0.956 |   0.991 |\n| interest_coverage           |     -0.086 |        0.042 |    -2.075 |      0.038 |  -0.168 |  -0.005 |\n| working_capital_to_assets   |     -2.079 |        1.247 |    -1.667 |      0.096 |  -4.524 |   0.366 |\n| retained_earnings_to_assets |     -2.011 |        0.958 |    -2.098 |      0.036 |  -3.889 |  -0.133 |\n---\nDeviance: 198.241 \n```\n:::\n:::\n\n\n::: {#7ace5f9e .cell execution_count=26}\n``` {.python .cell-code}\nmodel_2.tidy()\n```\n\n::: {.cell-output .cell-output-display execution_count=134}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Estimate</th>\n      <th>Std. Error</th>\n      <th>t value</th>\n      <th>Pr(&gt;|t|)</th>\n      <th>2.5%</th>\n      <th>97.5%</th>\n    </tr>\n    <tr>\n      <th>Coefficient</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>-0.566756</td>\n      <td>0.850955</td>\n      <td>-0.666024</td>\n      <td>5.053960e-01</td>\n      <td>-2.234597</td>\n      <td>1.101085</td>\n    </tr>\n    <tr>\n      <th>current_ratio</th>\n      <td>-0.885488</td>\n      <td>0.258488</td>\n      <td>-3.425646</td>\n      <td>6.133381e-04</td>\n      <td>-1.392115</td>\n      <td>-0.378861</td>\n    </tr>\n    <tr>\n      <th>debt_to_equity</th>\n      <td>2.100229</td>\n      <td>0.364566</td>\n      <td>5.760905</td>\n      <td>8.366416e-09</td>\n      <td>1.385693</td>\n      <td>2.814765</td>\n    </tr>\n    <tr>\n      <th>roa</th>\n      <td>-9.955580</td>\n      <td>2.487427</td>\n      <td>-4.002361</td>\n      <td>6.271354e-05</td>\n      <td>-14.830847</td>\n      <td>-5.080313</td>\n    </tr>\n    <tr>\n      <th>net_margin</th>\n      <td>-8.285320</td>\n      <td>2.217174</td>\n      <td>-3.736883</td>\n      <td>1.863154e-04</td>\n      <td>-12.630901</td>\n      <td>-3.939739</td>\n    </tr>\n    <tr>\n      <th>asset_turnover</th>\n      <td>0.017232</td>\n      <td>0.496592</td>\n      <td>0.034700</td>\n      <td>9.723188e-01</td>\n      <td>-0.956070</td>\n      <td>0.990533</td>\n    </tr>\n    <tr>\n      <th>interest_coverage</th>\n      <td>-0.086300</td>\n      <td>0.041594</td>\n      <td>-2.074849</td>\n      <td>3.800056e-02</td>\n      <td>-0.167822</td>\n      <td>-0.004778</td>\n    </tr>\n    <tr>\n      <th>working_capital_to_assets</th>\n      <td>-2.079107</td>\n      <td>1.247389</td>\n      <td>-1.666767</td>\n      <td>9.556068e-02</td>\n      <td>-4.523944</td>\n      <td>0.365730</td>\n    </tr>\n    <tr>\n      <th>retained_earnings_to_assets</th>\n      <td>-2.010975</td>\n      <td>0.958423</td>\n      <td>-2.098213</td>\n      <td>3.588634e-02</td>\n      <td>-3.889448</td>\n      <td>-0.132501</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-distress .cell execution_count=27}\n``` {.python .cell-code}\nmodel_2.coefplot()\n```\n\n::: {.cell-output .cell-output-display execution_count=135}\n![Factors Affecting Financial Distress of a Company](12-predictive-modeling-intro_files/figure-html/fig-distress-output-1.png){#fig-distress width=959 height=566}\n:::\n:::\n\n\n:::\n\n\n\n::: {.panel-tabset}\n## seaborn\n\n::: {#71675ec8 .cell execution_count=28}\n``` {.python .cell-code}\nplt.figure(figsize=(7, 4.5))\nsns.barplot(\n    data=coef_df, x=\"coefficient\", y=\"feature\", hue=\"direction\",\n    palette={\"Increases Risk\": \"#c9482f\", \"Decreases Risk\": \"#1c7c73\"}, legend=False\n)\nplt.title(\"Logistic Regression Coefficients (standardized features)\")\nplt.axvline(0, color=\"black\", linewidth=0.8)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](12-predictive-modeling-intro_files/figure-html/cell-29-output-1.png){width=680 height=422}\n:::\n:::\n\n\n## plotnine\n\n::: {#2f2a43ff .cell execution_count=29}\n``` {.python .cell-code}\n(\n    ggplot(coef_df, aes(x=\"reorder(feature, coefficient)\", y=\"coefficient\", fill=\"direction\"))\n    + geom_col()\n    + coord_flip()\n    + scale_fill_manual(values={\"Increases Risk\": \"#c9482f\", \"Decreases Risk\": \"#1c7c73\"})\n    + labs(title=\"Logistic Regression Coefficients (standardized features)\", x=\"\", y=\"Coefficient\", fill=\"\")\n    + theme_minimal()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=137}\n![](12-predictive-modeling-intro_files/figure-html/cell-30-output-1.png){width=672 height=480}\n:::\n:::\n\n\n:::\n\n`debt_to_equity` has the largest positive coefficient (higher leverage → higher distress risk), while `current_ratio` and `roa` show the largest negative coefficients (more liquidity and profitability → lower risk) — all consistent with the differences we saw in the group comparison above. @fig-distress presents the importance of coefficients. \n\n### Evaluating the Model\n\n::: {#270386e7 .cell execution_count=30}\n``` {.python .cell-code}\nfrom sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix\n\nyc_pred = clf_model.predict(Xc_test_scaled)\nyc_prob = clf_model.predict_proba(Xc_test_scaled)[:, 1]\n\nprint(\"Accuracy: \", round(accuracy_score(yc_test, yc_pred), 3))\nprint(\"Precision:\", round(precision_score(yc_test, yc_pred), 3))\nprint(\"Recall:   \", round(recall_score(yc_test, yc_pred), 3))\nprint(\"F1:       \", round(f1_score(yc_test, yc_pred), 3))\nprint(\"ROC-AUC:  \", round(roc_auc_score(yc_test, yc_prob), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAccuracy:  0.887\nPrecision: 0.75\nRecall:    0.462\nF1:        0.571\nROC-AUC:   0.836\n```\n:::\n:::\n\n\n::: {.callout-important}\n## The Accuracy Trap\n88.8% accuracy sounds impressive — until you notice that simply predicting \"no distress\" for *every single company* would already achieve **83.75% accuracy**, since only about 16% of companies in the test set are actually distressed. Our model's real improvement over that naive baseline is much smaller than the headline accuracy number suggests.\n\nThis is exactly why **precision, recall, and ROC-AUC matter more than accuracy alone** whenever the outcome you're predicting is rare — which describes most consequential accounting prediction problems (fraud, bankruptcy, default). A model can post a very high accuracy score while still being nearly useless at its actual job: identifying the rare cases that matter.\n:::\n\n::: {#eb060ff8 .cell execution_count=31}\n``` {.python .cell-code}\nbaseline_accuracy = 1 - yc_test.mean()\nprint(f\"Baseline accuracy (always predict 'no distress'): {baseline_accuracy:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBaseline accuracy (always predict 'no distress'): 0.838\n```\n:::\n:::\n\n\nOur **recall** of roughly 0.46 means the model correctly identifies fewer than half of the companies that actually become distressed — a real limitation worth stating plainly rather than glossing over.\n\n### Confusion Matrix and ROC Curve\n\n::: {#79382d3a .cell execution_count=32}\n``` {.python .cell-code}\ncm = confusion_matrix(yc_test, yc_pred)\ncm_df = pd.DataFrame(\n    cm,\n    index=[\"Actual: No Distress\", \"Actual: Distress\"],\n    columns=[\"Pred: No Distress\", \"Pred: Distress\"],\n)\ncm_df\n```\n\n::: {.cell-output .cell-output-display execution_count=140}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Pred: No Distress</th>\n      <th>Pred: Distress</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Actual: No Distress</th>\n      <td>65</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>Actual: Distress</th>\n      <td>7</td>\n      <td>6</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cc25b9ef .cell execution_count=33}\n``` {.python .cell-code}\nplt.figure(figsize=(5, 4))\nsns.heatmap(cm_df, annot=True, fmt=\"d\", cmap=\"Blues\")\nplt.title(\"Confusion Matrix\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](12-predictive-modeling-intro_files/figure-html/cell-34-output-1.png){width=448 height=374}\n:::\n:::\n\n\n::: {#85a8e053 .cell execution_count=34}\n``` {.python .cell-code}\nfrom sklearn.metrics import roc_curve\n\nfpr, tpr, thresholds = roc_curve(yc_test, yc_prob)\nroc_df = pd.DataFrame({\"fpr\": fpr, \"tpr\": tpr})\n```\n:::\n\n\n::: {.panel-tabset}\n## seaborn\n\n::: {#6a77d156 .cell execution_count=35}\n``` {.python .cell-code}\nplt.figure(figsize=(5.5, 5))\nplt.plot(fpr, tpr, color=\"#c9482f\", label=\"Logistic Regression\")\nplt.plot([0, 1], [0, 1], \"--\", color=\"gray\", label=\"Random guess\")\nplt.xlabel(\"False Positive Rate\")\nplt.ylabel(\"True Positive Rate\")\nplt.title(\"ROC Curve: Predicting Financial Distress\")\nplt.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](12-predictive-modeling-intro_files/figure-html/cell-36-output-1.png){width=520 height=470}\n:::\n:::\n\n\n## plotnine\n\n::: {#5f058cf8 .cell execution_count=36}\n``` {.python .cell-code}\n(\n    ggplot(roc_df, aes(x=\"fpr\", y=\"tpr\"))\n    + geom_line(color=\"#c9482f\", size=1)\n    + geom_abline(slope=1, intercept=0, linetype=\"dashed\", color=\"gray\")\n    + labs(title=\"ROC Curve: Predicting Financial Distress\", x=\"False Positive Rate\", y=\"True Positive Rate\")\n    + theme_minimal()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=144}\n![](12-predictive-modeling-intro_files/figure-html/cell-37-output-1.png){width=672 height=480}\n:::\n:::\n\n\n:::\n\nA ROC-AUC of 0.84 means the model does meaningfully better than random guessing at ranking companies by risk (an AUC of 0.5 would be no better than a coin flip), even though its **recall** at the default 50% probability threshold is modest. This is a useful reminder that a model's *ranking* ability and its performance at any *one specific threshold* are related but distinct questions — a point we return to in the exercises.\n\n## Chapter Summary\n\n- Predictive analytics uses historical data to estimate an outcome that hasn't happened yet, building on the descriptive and diagnostic foundations from earlier chapters.\n- Regression predicts a continuous outcome (days to collect); classification predicts a categorical outcome (financial distress) — the right choice depends entirely on the nature of the outcome you're trying to predict.\n- Splitting data into training and test sets is essential for honestly evaluating whether a model generalizes, rather than just memorizing the data it was fit on.\n- A weak regression result (R² of 0.14) is a legitimate and informative finding — not every prediction problem yields a strong model, and honestly reporting a weak fit is more valuable than manufacturing an artificially strong one.\n- Standardizing features before logistic regression puts coefficients on a comparable scale, making it possible to compare which factors matter most.\n- With imbalanced outcomes (here, ~17% distress), accuracy alone can be deeply misleading — a naive \"always predict the majority class\" baseline can already achieve high accuracy, so precision, recall, F1, and ROC-AUC are essential companions to any accuracy figure.\n\n## Discussion Questions\n\n1. The regression model's R² was only 0.14. If you were presenting this result to a manager who wanted a \"good\" model, how would you explain why this result is still useful, rather than a failure?\n2. Our classification model's recall was about 0.46 — it misses more than half of truly distressed companies. If you were designing a real early-warning system, would you rather have higher recall (catch more distressed companies, at the cost of more false alarms) or higher precision (fewer false alarms, but miss more real cases)? What accounting or business context would change your answer?\n3. Explain, in your own words, why a model can have high accuracy but still be practically useless, using the baseline accuracy comparison from this chapter as your example.\n\n## Exercises\n\n1. Add `quarter` as a categorical (one-hot encoded) feature instead of a numeric one in the regression model. Does R² improve, and does the interpretation of the `quarter` effect change?\n2. Refit the logistic regression model using only four features of your choice (rather than all eight). How much do accuracy, recall, and ROC-AUC change compared to the full model?\n3. The default classification threshold is 50% predicted probability. Using `clf_model.predict_proba()`, manually apply a lower threshold (e.g., 30%) to classify companies as distressed, and recompute precision and recall. How do they change, and why?\n4. Using `paid_pd`, engineer one new feature not used in this chapter (for example, a flag for whether the customer is one of the four high-risk customers identified in Chapter 10) and add it to the regression model. Does it improve R² meaningfully?\n\n",
    "supporting": [
      "12-predictive-modeling-intro_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}