{
  "hash": "ebd1f27a225404b298490ce01c484df1",
  "result": {
    "engine": "jupyter",
    "markdown": "# Generative AI in Accounting\n\n\n::: {.callout-note}\n## Learning Objectives\nBy the end of this chapter, you should be able to:\n\n- Explain how generative AI differs from the predictive models built in Chapter 12\n- Describe current, real-world use cases for generative AI in accounting and audit practice\n- Apply basic prompt engineering principles to accounting-specific tasks\n- Use an LLM API from Python to draft narrative content from computed financial data\n- Systematically verify AI-generated content against source data, rather than trusting it by default\n- Identify the key risks of using generative AI in accounting work: hallucination, confidentiality, bias, and overreliance\n- Describe the current regulatory and professional landscape around AI use in audit and financial reporting\n:::\n\n## Generative AI vs. the Predictive Models in Chapter 12\n\nChapter 12 built models that predict a specific, narrow output from structured, numeric data: a number of days, a probability of distress. **Generative AI** — large language models (LLMs) like Claude, GPT, or Gemini — work differently: they're trained to produce open-ended, human-like text (or images, code, and other content) in response to a prompt, rather than a single predicted value.\n\nThis distinction matters practically. A logistic regression model can tell you *a company's probability of financial distress*, computed from specific numeric inputs, and that number is fully determined by the data and the model's fitted coefficients. An LLM asked to *write a paragraph about a company's financial health* will produce fluent, plausible-sounding prose — but that prose is generated by predicting likely word sequences, not by performing the underlying arithmetic itself, even if the numbers happen to appear correct. This is the source of nearly every risk discussed in this chapter, and it's worth keeping in mind throughout.\n\n## Current Use Cases in Accounting and Audit Practice\n\nGenerative AI is already in active, if still early-stage, use across the profession:\n\n- **Audit documentation and workpaper drafting** — summarizing findings, drafting standard sections of workpapers from structured inputs\n- **Anomaly explanation** — after a statistical or rule-based test (like the ones in Chapters 8-9) flags a transaction, an LLM can help draft a plain-language summary of *why* it was flagged, to speed up reviewer triage\n- **Disclosure and financial narrative drafting** — drafting first-pass MD&A commentary, footnote language, or management representation letters, always subject to human review\n- **Tax research assistance** — summarizing tax code sections or prior guidance as a starting point for a human researcher, not a final answer\n- **Client communication drafting** — first drafts of client memos, follow-up questions, or engagement letters\n\n::: {.callout-tip}\n## Connect to Practice\nEvery one of these use cases follows the same pattern: **AI drafts, a human verifies.** None of them involve an LLM independently reaching a final conclusion that goes into a financial statement or audit opinion without review. That pattern isn't a limitation to work around — it's the appropriate way to use this technology given the risks covered later in this chapter.\n:::\n\n## Prompt Engineering Basics for Accounting Tasks\n\nThe quality of an LLM's output depends heavily on how you ask. A few principles that matter especially for accounting tasks:\n\n- **Be specific about format and audience.** \"Summarize this\" produces something different from \"Summarize this in three bullet points for a non-technical audit committee member.\"\n- **Provide the actual data, don't just describe it.** An LLM asked to comment on \"a company with declining margins\" will invent plausible-sounding but fictional specifics. An LLM given the actual computed ratios can reference them directly — though as we'll see, \"given the numbers\" doesn't guarantee it will use them correctly.\n- **Ask for a specific structure.** Requesting a fixed structure (e.g., \"one paragraph on profitability, one on leverage, one flagged concern\") produces more consistent, checkable output than an open-ended request.\n- **State what *not* to do.** Explicitly asking a model not to invent figures it wasn't given, and to flag uncertainty rather than guessing, measurably reduces (though does not eliminate) fabricated details.\n\n## Hands-On: Drafting a Financial Narrative with an LLM API\n\nLet's connect this directly to Chapter 7's ratio analysis. We'll recompute this company's 2025 ratios, then use them to prompt an LLM to draft a short narrative — exactly the kind of first-draft assistance described above.\n\n:::{.panel-tabset}\n## pandas \n\n::: {.cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\n\ninc = pd.read_csv(\"data/income_statement.csv\")\nbs = pd.read_csv(\"data/balance_sheet.csv\")\nmerged = inc.merge(bs, on=\"year\")\n\nratios = pd.DataFrame({\"year\": merged[\"year\"]})\nratios[\"net_margin\"] = merged[\"Net Income\"] / merged[\"Revenue\"]\nratios[\"current_ratio\"] = merged[\"Total Current Assets\"] / merged[\"Total Current Liabilities\"]\nratios[\"debt_to_equity\"] = (merged[\"Short-term Debt\"] + merged[\"Long-term Debt\"]) / merged[\"Total Equity\"]\n\nlatest = ratios.iloc[-1]\nlatest.round(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nyear              2025.000\nnet_margin           0.158\ncurrent_ratio        7.369\ndebt_to_equity       0.068\nName: 4, dtype: float64\n```\n:::\n:::\n\n\n## polars \n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\nimport polars as pl\n\n# Read the data\ninc_pl = pl.read_csv(\"data/income_statement.csv\")\nbs_pl = pl.read_csv(\"data/balance_sheet.csv\")\n\n# Merge the two DataFrames\nmerged_pl = inc_pl.join(\n    bs_pl,\n    on=\"year\",\n    how=\"inner\"\n)\n\n# Compute financial ratios\nratios_pl = (\n    merged_pl\n    .select(\n        \"year\",\n\n        (\n            pl.col(\"Net Income\")\n            / pl.col(\"Revenue\")\n        ).alias(\"net_margin\"),\n\n        (\n            pl.col(\"Total Current Assets\")\n            / pl.col(\"Total Current Liabilities\")\n        ).alias(\"current_ratio\"),\n\n        (\n            (pl.col(\"Short-term Debt\") + pl.col(\"Long-term Debt\"))\n            / pl.col(\"Total Equity\")\n        ).alias(\"debt_to_equity\"),\n    )\n)\n\n# Get the latest year\nlatest_pl = (\n    ratios_pl\n    .sort(\"year\")\n    .tail(1)\n    .with_columns(\n        pl.exclude(\"year\").round(3)\n    )\n)\n\nlatest_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (1, 4)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>net_margin</th><th>current_ratio</th><th>debt_to_equity</th></tr><tr><td>i64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>2025</td><td>0.158</td><td>7.369</td><td>0.068</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\n# This chunk requires your own Anthropic API key and will not run automatically\n# when this book is rendered. Install the SDK first: pip install anthropic\nimport anthropic\n\nclient = anthropic.Anthropic(api_key=\"YOUR_API_KEY_HERE\")\n\nprompt = f\"\"\"\nUsing ONLY the figures provided below, write a two-sentence summary of this\ncompany's 2025 financial position for a non-technical reader. Do not invent\nany numbers not given here. If you are uncertain about an interpretation,\nsay so explicitly rather than guessing.\n\nNet margin: {latest['net_margin']:.1%}\nCurrent ratio: {latest['current_ratio']:.2f}\nDebt-to-equity: {latest['debt_to_equity']:.2f}\n\"\"\"\n\n# NOTE: check https://docs.claude.com for the current model name before running\nresponse = client.messages.create(\n    model=\"claude-sonnet-4-5\",\n    max_tokens=300,\n    messages=[{\"role\": \"user\", \"content\": prompt}],\n)\n\nprint(response.content[0].text)\n```\n:::\n\n\n::: {.callout-important}\n## Why This Code Isn't Executed in This Book\nThe chunk above is marked `eval: false`, meaning it's shown for reference but doesn't run when this book renders — it requires your own API key, which shouldn't be hardcoded into a shared document. When you run this yourself, store your key as an environment variable (`os.environ[\"ANTHROPIC_API_KEY\"]`) rather than typing it directly into a notebook or `.qmd` file, especially one that might end up in a shared Git repository, as yours already is.\n:::\n\n## The Hallucination Check: Verifying AI Output Against Source Data\n\nSuppose the model above returned the following (this is a realistic example of the kind of output an LLM might produce, written here for teaching purposes):\n\n> *\"This company shows strong and improving profitability, with net margin reaching 18.2% in 2025. Liquidity is very strong, with a current ratio of 7.37, and the company carries minimal financial risk with a debt-to-equity ratio of 0.07.\"*\n\nThis paragraph reads fluently and looks well-supported by numbers. It's also **subtly wrong** — one figure doesn't match what we actually computed. Let's check it the way you should check any AI-generated content containing numbers: line by line, against the source data.\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\nai_claims = {\n    \"net_margin\": 0.182,\n    \"current_ratio\": 7.37,\n    \"debt_to_equity\": 0.07,\n}\n\nactual_values = {\n    \"net_margin\": round(latest[\"net_margin\"], 4),\n    \"current_ratio\": round(latest[\"current_ratio\"], 2),\n    \"debt_to_equity\": round(latest[\"debt_to_equity\"], 2),\n}\n\nfor metric, claimed in ai_claims.items():\n    actual = actual_values[metric]\n    match = abs(claimed - actual) < 0.005\n    print(f\"{metric}: claimed={claimed}, actual={actual}, matches={match}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnet_margin: claimed=0.182, actual=0.1576, matches=False\ncurrent_ratio: claimed=7.37, actual=7.37, matches=True\ndebt_to_equity: claimed=0.07, actual=0.07, matches=True\n```\n:::\n:::\n\n\nThe `net_margin` claim of 18.2% doesn't match our actual computed value of 15.8% — a **hallucinated figure** that looks entirely plausible sitting next to two genuinely correct numbers. This is exactly what makes numeric hallucination dangerous in practice: a reader has no visual cue that one number in a paragraph is fabricated while the others are accurate. The only reliable defense is checking every figure against its source, every time — not spot-checking the ones that \"feel\" wrong.\n\n::: {.callout-important}\n## Why LLMs Make This Kind of Mistake\nAn LLM generates text by predicting plausible word (and number) sequences based on patterns in its training data, not by running a calculator. Even when given the correct inputs directly in a prompt, it can still produce a number that *sounds* right — close to the correct order of magnitude, formatted correctly — without it actually being the number it was given. This is fundamentally different from a calculation error in a spreadsheet formula, which is at least deterministic and reproducible; an LLM's numeric error can vary from one run to the next even with an identical prompt.\n:::\n\n## Using GenAI for Synthetic Text Generation\n\nIt's worth distinguishing two different things people mean by \"synthetic data\":\n\n- **Statistical/numeric simulation** — generating realistic numeric datasets by sampling from probability distributions (this is exactly how every dataset in this book was built: lognormal transaction amounts, logistic financial distress probabilities, and so on). This is a traditional statistical technique, not generative AI.\n- **AI-generated text content** — using an LLM to generate realistic *unstructured* text: transaction descriptions, vendor names, customer complaint narratives, or email bodies for a training exercise. This is where generative AI genuinely adds something numeric simulation can't easily produce.\n\nFor example, an LLM is well-suited to generating a batch of realistic-sounding (but fictional) journal entry descriptions for a classroom exercise — \"Q3 marketing consulting services - Contract #4471\" reads far more like a real transaction memo than anything a random word generator would produce. But note that an LLM is a poor tool for generating the *dollar amounts* in that same dataset — that's exactly the kind of numeric task better suited to the statistical simulation techniques used throughout this book.\n\n## Risks and Limitations\n\n- **Hallucination on numeric data.** As demonstrated above, LLMs can generate plausible-looking but incorrect figures, even when given correct source data. Never treat an AI-generated number as verified until you've checked it yourself.\n- **Confidentiality and data privacy.** Pasting real client financial data, employee information, or unpublished results into a public AI tool can violate client confidentiality agreements or data privacy regulations. Firms increasingly require using only approved, firm-licensed AI tools with appropriate data handling agreements, not general consumer AI products, for any real client data.\n- **Bias.** LLMs are trained on large text corpora that can encode historical biases; this is a concern for any application involving people (e.g., drafting language about employee performance or credit decisions), not just financial figures.\n- **Overreliance and automation complacency.** Repeated correct AI output can lead reviewers to reduce their scrutiny over time — the exact failure mode that led to the \"AI drafts, a human verifies\" principle in the first place. A review process that exists on paper but isn't actually performed provides no real protection.\n\n## The Current Regulatory and Professional Landscape\n\nThis is a fast-moving area, and any specific description risks going stale — but as of mid-2026, a few themes are consistent across regulators:\n\n- The **PCAOB** issued staff guidance addressing AI use from two angles: when audit firms use AI in their own procedures (requiring documentation and supervision sufficient for a reviewer to understand what the tool did and how its output was evaluated), and when audit clients themselves use AI in their financial reporting processes (requiring auditors to understand and evaluate those systems, similar to existing IT general control expectations) [PCAOB -@public_company_accounting_oversight_board_pcaob_staff_2024].\n- The **SEC** launched an internal AI Task Force in 2025 focused on the agency's own use of AI, and its Division of Corporation Finance has reportedly begun including AI-related questions in comment letters to registrants about AI governance and risk disclosures — without yet finalizing a specific AI disclosure rule for financial reporting [US SEC -@us_securities__exchange_commission_us_sec_sec_2025].\n- Internationally, the **IAASB** has been developing updated technology-specific guidance, building on existing standards for understanding IT systems and automated controls [IAASB -@the_international_auditing_and_assurance_standards_board_iaasb_iaasb_2024].\n\n::: {.callout-tip}\n## Connect to Practice\nBecause this area changes quickly, treat any specific claim here as a starting point for your own research, not a final answer — exactly the same \"AI drafts, verify independently\" discipline this chapter has emphasized throughout. Check the PCAOB's and SEC's own websites for the most current guidance before relying on this for real engagement decisions.\n:::\n\n## Designing an \"AI vs. Analyst\" Exercise\n\nA useful way to build critical judgment about AI output is a structured comparison exercise:\n\n1. Give the same financial dataset to a human analyst (or yourself) and to an LLM, with the same prompt/task (e.g., \"identify the three most significant financial statement changes and their likely causes\").\n2. Have each work independently — the analyst without seeing the AI's draft first.\n3. Compare: What did each get right? Did the AI fabricate or misstate any figures? Did the human miss a pattern the AI caught (or vice versa)?\n4. Discuss: where would you trust the AI's output directly, where would you want independent verification, and why?\n\nThis exercise works well applied to any dataset from this book — for example, Chapter 7's five-year ratio trends, or Chapter 8's flagged transactions — precisely because you already know the \"correct\" answer independently and can grade both outputs against it.\n\n## Chapter Summary\n\n- Generative AI produces open-ended text by predicting plausible sequences, unlike the predictive models in Chapter 12, which compute a specific output from a fitted statistical relationship — this distinction explains most of the risks in this chapter.\n- Current accounting and audit use cases follow a consistent pattern: AI drafts, a human verifies — anomaly explanations, disclosure drafting, and research assistance, not final unsupervised conclusions.\n- Effective prompts for accounting tasks are specific about format and audience, provide actual data rather than descriptions of it, request a defined structure, and explicitly instruct the model not to invent figures.\n- AI-generated numeric claims must be verified against source data individually — a hallucinated figure can sit undetected next to entirely correct ones, with no stylistic cue distinguishing them.\n- Generative AI is well-suited to producing realistic unstructured text (descriptions, narratives) but poorly suited to generating numeric data, which is better handled by the statistical simulation techniques used throughout this book.\n- Confidentiality, bias, and automation complacency are risks independent of hallucination, and each requires its own safeguard rather than being solved by \"just checking the numbers.\"\n- Regulatory guidance (PCAOB, SEC, IAASB) is actively developing but not yet fully settled — current as of this writing, but worth verifying directly before relying on it professionally.\n\n## Discussion Questions\n\n1. Why might an LLM produce a hallucinated number even when given the correct figures directly in the prompt, rather than only when working from memory?\n2. The chapter distinguishes AI-generated text from statistical numeric simulation. Can you think of an accounting task where you'd want to combine both — using an LLM for some part of a dataset and statistical simulation for another?\n3. If your firm required all AI-assisted workpapers to document \"what the tool did and how its output was evaluated,\" what would that documentation look like for the hallucination-check exercise performed in this chapter?\n\n## Exercises\n\n1. Using this chapter's `latest` ratios (or any other chapter's computed figures), write your own deliberately flawed AI-style paragraph containing exactly one incorrect figure, then write the verification code to catch it — the way the hallucination-check example did in this chapter.\n2. Draft two versions of a prompt asking an LLM to summarize Chapter 9's fraud detection results: one vague (\"tell me about this data\") and one following this chapter's prompt engineering principles (specific format, actual data included, explicit instruction not to invent figures). If you have API access, run both and compare; if not, predict in writing how the outputs would likely differ.\n3. Design your own \"AI vs. Analyst\" exercise (following this chapter's structure) using Chapter 11's tax jurisdiction data. What's the \"correct answer\" you'd grade both outputs against?\n4. Research your firm's (or a firm you're familiar with, or a hypothetical one) policy on using AI tools with client data. Write a short (150-word) summary of what it permits, what it prohibits, and whether it matches the confidentiality concerns raised in this chapter.\n\n",
    "supporting": [
      "14-genai-in-accounting_files\\figure-pdf"
    ],
    "filters": []
  }
}