{
  "hash": "2aea6a8f571b05ab31fffa2d5929b32b",
  "result": {
    "engine": "jupyter",
    "markdown": "# Financial Statement Analytics\n\n\n::: {.callout-note}\n## Learning Objectives\nBy the end of this chapter, you should be able to:\n\n- Load and structure multi-year financial statement data for analysis\n- Perform horizontal (trend) analysis and vertical (common-size) analysis\n- Compute liquidity, profitability, leverage, and efficiency ratios\n- Build a reusable function that automates ratio calculations across any set of financial statements\n- Apply DuPont decomposition to explain *why* return on equity changed, not just that it changed\n- Interpret ratio trends critically, rather than treating any single ratio as a verdict on its own\n:::\n\n## From General Ledger to Financial Statements\n\nChapters 3 and 4 traced how transactions flow from the general ledger into a trial balance. Financial statements are the next and final step in that chain: the income statement summarizes revenue and expense activity for a period, and the balance sheet summarizes assets, liabilities, and equity at a point in time.\n\nThis chapter works with **five years of financial statements (2021–2025)** for a fictional company, \"Ledger & Co.,\" stored in `income_statement.csv` and `balance_sheet.csv`. Unlike the transaction-level data from earlier chapters, this data is already fully summarized — each row is one fiscal year, and each column is a financial statement line item.\n\n::: {.panel-tabset}\n## pandas \n\n::: {#56b058c1 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\n\ninc = pd.read_csv(\"data/income_statement.csv\")\nbs = pd.read_csv(\"data/balance_sheet.csv\")\n\ninc\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>Revenue</th>\n      <th>Cost of Goods Sold</th>\n      <th>Gross Profit</th>\n      <th>Operating Expenses (SG&amp;A)</th>\n      <th>Depreciation and Amortization</th>\n      <th>Operating Income</th>\n      <th>Interest Expense</th>\n      <th>Pretax Income</th>\n      <th>Income Tax Expense</th>\n      <th>Net Income</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2021</td>\n      <td>4200000</td>\n      <td>2604000</td>\n      <td>1596000</td>\n      <td>882000</td>\n      <td>95000</td>\n      <td>619000</td>\n      <td>62000</td>\n      <td>557000</td>\n      <td>116970</td>\n      <td>440030</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2022</td>\n      <td>4850000</td>\n      <td>2982750</td>\n      <td>1867250</td>\n      <td>994250</td>\n      <td>105000</td>\n      <td>768000</td>\n      <td>58000</td>\n      <td>710000</td>\n      <td>149100</td>\n      <td>560900</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2023</td>\n      <td>5450000</td>\n      <td>3270000</td>\n      <td>2180000</td>\n      <td>1090000</td>\n      <td>118000</td>\n      <td>972000</td>\n      <td>52000</td>\n      <td>920000</td>\n      <td>193200</td>\n      <td>726800</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2024</td>\n      <td>6100000</td>\n      <td>3629500</td>\n      <td>2470500</td>\n      <td>1189500</td>\n      <td>128000</td>\n      <td>1153000</td>\n      <td>44000</td>\n      <td>1109000</td>\n      <td>232890</td>\n      <td>876110</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2025</td>\n      <td>6900000</td>\n      <td>4036500</td>\n      <td>2863500</td>\n      <td>1311000</td>\n      <td>140000</td>\n      <td>1412500</td>\n      <td>36000</td>\n      <td>1376500</td>\n      <td>289065</td>\n      <td>1087435</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars \n\n::: {#7b12a432 .cell execution_count=2}\n``` {.python .cell-code}\nimport polars as pl\ninc_pl = pl.read_csv(\"data/income_statement.csv\")\nbs_pl = pl.read_csv(\"data/balance_sheet.csv\")\nbs_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 16)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Cash</th><th>Accounts Receivable</th><th>Inventory</th><th>Property, Plant &amp; Equipment (net)</th><th>Accounts Payable</th><th>Short-term Debt</th><th>Long-term Debt</th><th>Common Stock</th><th>Retained Earnings</th><th>Total Current Assets</th><th>Total Assets</th><th>Total Current Liabilities</th><th>Total Liabilities</th><th>Total Equity</th><th>Total Liabilities and Equity</th></tr><tr><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td></tr></thead><tbody><tr><td>2021</td><td>461051</td><td>483288</td><td>392384</td><td>675000</td><td>249699</td><td>80000</td><td>450000</td><td>500000</td><td>732024</td><td>1336723</td><td>2011723</td><td>329699</td><td>779699</td><td>1232024</td><td>2011723</td></tr><tr><td>2022</td><td>763486</td><td>531507</td><td>424940</td><td>730000</td><td>294189</td><td>75000</td><td>400000</td><td>500000</td><td>1180744</td><td>1719933</td><td>2449933</td><td>369189</td><td>769189</td><td>1680744</td><td>2449933</td></tr><tr><td>2023</td><td>1186389</td><td>582329</td><td>447945</td><td>787000</td><td>331479</td><td>70000</td><td>340000</td><td>500000</td><td>1762184</td><td>2216663</td><td>3003663</td><td>401479</td><td>741479</td><td>2262184</td><td>3003663</td></tr><tr><td>2024</td><td>1719566</td><td>635068</td><td>477304</td><td>844000</td><td>377866</td><td>65000</td><td>270000</td><td>500000</td><td>2463072</td><td>2831938</td><td>3675938</td><td>442866</td><td>712866</td><td>2963072</td><td>3675938</td></tr><tr><td>2025</td><td>2412155</td><td>699452</td><td>508710</td><td>904000</td><td>431297</td><td>60000</td><td>200000</td><td>500000</td><td>3333020</td><td>3620317</td><td>4524317</td><td>491297</td><td>691297</td><td>3833020</td><td>4524317</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\n::: {.panel-tabset}\n## pandas \n\n::: {#13fc6306 .cell execution_count=3}\n``` {.python .cell-code}\nbs[[\"year\", \"Cash\", \"Total Current Assets\", \"Total Assets\", \"Total Liabilities\", \"Total Equity\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>Cash</th>\n      <th>Total Current Assets</th>\n      <th>Total Assets</th>\n      <th>Total Liabilities</th>\n      <th>Total Equity</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2021</td>\n      <td>461051</td>\n      <td>1336723</td>\n      <td>2011723</td>\n      <td>779699</td>\n      <td>1232024</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2022</td>\n      <td>763486</td>\n      <td>1719933</td>\n      <td>2449933</td>\n      <td>769189</td>\n      <td>1680744</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2023</td>\n      <td>1186389</td>\n      <td>2216663</td>\n      <td>3003663</td>\n      <td>741479</td>\n      <td>2262184</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2024</td>\n      <td>1719566</td>\n      <td>2831938</td>\n      <td>3675938</td>\n      <td>712866</td>\n      <td>2963072</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2025</td>\n      <td>2412155</td>\n      <td>3620317</td>\n      <td>4524317</td>\n      <td>691297</td>\n      <td>3833020</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars \n\n::: {#847bdd21 .cell execution_count=4}\n``` {.python .cell-code}\nbs_pl.select(\"year\", \"Cash\", \"Total Current Assets\", \"Total Assets\", \"Total Liabilities\", \"Total Equity\")\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 6)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Cash</th><th>Total Current Assets</th><th>Total Assets</th><th>Total Liabilities</th><th>Total Equity</th></tr><tr><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td><td>i64</td></tr></thead><tbody><tr><td>2021</td><td>461051</td><td>1336723</td><td>2011723</td><td>779699</td><td>1232024</td></tr><tr><td>2022</td><td>763486</td><td>1719933</td><td>2449933</td><td>769189</td><td>1680744</td></tr><tr><td>2023</td><td>1186389</td><td>2216663</td><td>3003663</td><td>741479</td><td>2262184</td></tr><tr><td>2024</td><td>1719566</td><td>2831938</td><td>3675938</td><td>712866</td><td>2963072</td></tr><tr><td>2025</td><td>2412155</td><td>3620317</td><td>4524317</td><td>691297</td><td>3833020</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\n\n::: {.callout-tip}\n## A Note on Tools for This Chapter\nThis chapter uses pandas only. Financial statement data is small by nature — five rows, a few dozen columns — so polars' performance advantages (Chapter 4) don't come into play here the way they did with transaction-level general ledger data. Feel free to redo any of this chapter's calculations in polars as practice, but there's no analytical reason to prefer it for a dataset this size.\n:::\n\nBefore calculating anything, it's worth confirming the balance sheet actually balances — a basic sanity check you should run on any real financial statement data before trusting it:\n\n::: {.panel-tabset}\n## pandas \n\n::: {#4750925f .cell execution_count=5}\n``` {.python .cell-code}\nimbalance = bs[\"Total Assets\"] - bs[\"Total Liabilities and Equity\"]\nimbalance\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n0    0\n1    0\n2    0\n3    0\n4    0\ndtype: int64\n```\n:::\n:::\n\n\n## polars\n\n::: {#03200f1a .cell execution_count=6}\n``` {.python .cell-code}\nimbalance_pl = bs_pl.select(\"Total Assets\") - bs_pl.select(\"Total Liabilities and Equity\")\nimbalance_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 1)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Total Assets</th></tr><tr><td>i64</td></tr></thead><tbody><tr><td>0</td></tr><tr><td>0</td></tr><tr><td>0</td></tr><tr><td>0</td></tr><tr><td>0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\nEvery year balances exactly, as it should.\n\n## Horizontal (Trend) Analysis\n\n**Horizontal analysis** compares a line item across time, showing dollar and percentage change from one period to the next.\n\n::: {.panel-tabset}\n## pandas \n\n::: {#d428f518 .cell execution_count=7}\n``` {.python .cell-code}\nincome_by_year = inc.set_index(\"year\")\n\ndollar_change = income_by_year.diff()\ndollar_change[[\"Revenue\", \"Net Income\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Revenue</th>\n      <th>Net Income</th>\n    </tr>\n    <tr>\n      <th>year</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2021</th>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2022</th>\n      <td>650000.0</td>\n      <td>120870.0</td>\n    </tr>\n    <tr>\n      <th>2023</th>\n      <td>600000.0</td>\n      <td>165900.0</td>\n    </tr>\n    <tr>\n      <th>2024</th>\n      <td>650000.0</td>\n      <td>149310.0</td>\n    </tr>\n    <tr>\n      <th>2025</th>\n      <td>800000.0</td>\n      <td>211325.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#4da2ce90 .cell execution_count=8}\n``` {.python .cell-code}\npct_change = income_by_year.pct_change() * 100\npct_change[[\"Revenue\", \"Net Income\"]].round(1)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Revenue</th>\n      <th>Net Income</th>\n    </tr>\n    <tr>\n      <th>year</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2021</th>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2022</th>\n      <td>15.5</td>\n      <td>27.5</td>\n    </tr>\n    <tr>\n      <th>2023</th>\n      <td>12.4</td>\n      <td>29.6</td>\n    </tr>\n    <tr>\n      <th>2024</th>\n      <td>11.9</td>\n      <td>20.5</td>\n    </tr>\n    <tr>\n      <th>2025</th>\n      <td>13.1</td>\n      <td>24.1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars \n\n::: {#e783df4e .cell execution_count=9}\n``` {.python .cell-code}\ndollar_change_pl = (\n    inc_pl\n    .sort(\"year\")\n    .with_columns(\n        pl.col([\"Revenue\", \"Net Income\"]).diff()\n    )\n    .select([\"year\", \"Revenue\", \"Net Income\"])\n)\n\ndollar_change_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 3)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Revenue</th><th>Net Income</th></tr><tr><td>i64</td><td>i64</td><td>i64</td></tr></thead><tbody><tr><td>2021</td><td>null</td><td>null</td></tr><tr><td>2022</td><td>650000</td><td>120870</td></tr><tr><td>2023</td><td>600000</td><td>165900</td></tr><tr><td>2024</td><td>650000</td><td>149310</td></tr><tr><td>2025</td><td>800000</td><td>211325</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n::: {#8064d551 .cell execution_count=10}\n``` {.python .cell-code}\npct_change_pl = (\n    inc_pl\n    .sort(\"year\")\n    .with_columns(\n        (pl.col([\"Revenue\", \"Net Income\"]).pct_change() * 100).round(1)\n    )\n    .select([\"year\", \"Revenue\", \"Net Income\"])\n)\n\npct_change_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 3)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Revenue</th><th>Net Income</th></tr><tr><td>i64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>2021</td><td>null</td><td>null</td></tr><tr><td>2022</td><td>15.5</td><td>27.5</td></tr><tr><td>2023</td><td>12.4</td><td>29.6</td></tr><tr><td>2024</td><td>11.9</td><td>20.5</td></tr><tr><td>2025</td><td>13.1</td><td>24.1</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\nRevenue grew between 12% and 15% annually, but notice that **net income grew faster than revenue every year** (e.g., 27.5% net income growth vs. 15.5% revenue growth in 2022) — a sign that profitability is improving, not just sales volume. We'll confirm this more precisely with margin ratios shortly.\n\n### Indexed Trend Analysis\n\nA related technique sets the earliest year to 100 and expresses every later year relative to that baseline — useful for comparing the *relative* growth rate of several line items on one consistent scale, regardless of their different starting dollar amounts.\n\n::: {.panel-tabset}\n## pandas \n\n::: {#ce52b326 .cell execution_count=11}\n``` {.python .cell-code}\nindexed = income_by_year / income_by_year.iloc[0] * 100\nindexed[[\"Revenue\", \"Cost of Goods Sold\", \"Net Income\"]].round(1)\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Revenue</th>\n      <th>Cost of Goods Sold</th>\n      <th>Net Income</th>\n    </tr>\n    <tr>\n      <th>year</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2021</th>\n      <td>100.0</td>\n      <td>100.0</td>\n      <td>100.0</td>\n    </tr>\n    <tr>\n      <th>2022</th>\n      <td>115.5</td>\n      <td>114.5</td>\n      <td>127.5</td>\n    </tr>\n    <tr>\n      <th>2023</th>\n      <td>129.8</td>\n      <td>125.6</td>\n      <td>165.2</td>\n    </tr>\n    <tr>\n      <th>2024</th>\n      <td>145.2</td>\n      <td>139.4</td>\n      <td>199.1</td>\n    </tr>\n    <tr>\n      <th>2025</th>\n      <td>164.3</td>\n      <td>155.0</td>\n      <td>247.1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars \n\n::: {#e4a7c87e .cell execution_count=12}\n``` {.python .cell-code}\nindexed_pl = (\n    inc_pl\n    .sort(\"year\")\n    .with_columns(\n        (\n            pl.col([\"Revenue\", \"Cost of Goods Sold\", \"Net Income\"])\n            / pl.col([\"Revenue\", \"Cost of Goods Sold\", \"Net Income\"]).first()\n            * 100\n        ).round(1)\n    )\n    .select([\"Revenue\", \"Cost of Goods Sold\", \"Net Income\"])\n)\n\nindexed_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 3)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>Revenue</th><th>Cost of Goods Sold</th><th>Net Income</th></tr><tr><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>100.0</td><td>100.0</td><td>100.0</td></tr><tr><td>115.5</td><td>114.5</td><td>127.5</td></tr><tr><td>129.8</td><td>125.6</td><td>165.2</td></tr><tr><td>145.2</td><td>139.4</td><td>199.1</td></tr><tr><td>164.3</td><td>155.0</td><td>247.1</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\nBy 2025, revenue has grown to 164% of its 2021 level, while net income has grown to 247% of its 2021 level — again showing that profitability is compounding faster than the top line.\n\n## Vertical (Common-Size) Analysis\n\n**Vertical analysis** expresses every line item as a percentage of a single base figure within the same year — typically revenue for the income statement, and total assets for the balance sheet. This is especially useful for comparing structure across years (or across companies of different sizes) without dollar amounts getting in the way.\n\n::: {.panel-tabset}\n## pandas \n\n::: {#75660f14 .cell execution_count=13}\n``` {.python .cell-code}\ncommon_size_is = income_by_year.div(income_by_year[\"Revenue\"], axis=0) * 100\ncommon_size_is[[\"Cost of Goods Sold\", \"Gross Profit\", \"Operating Income\", \"Net Income\"]].round(1)\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Cost of Goods Sold</th>\n      <th>Gross Profit</th>\n      <th>Operating Income</th>\n      <th>Net Income</th>\n    </tr>\n    <tr>\n      <th>year</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2021</th>\n      <td>62.0</td>\n      <td>38.0</td>\n      <td>14.7</td>\n      <td>10.5</td>\n    </tr>\n    <tr>\n      <th>2022</th>\n      <td>61.5</td>\n      <td>38.5</td>\n      <td>15.8</td>\n      <td>11.6</td>\n    </tr>\n    <tr>\n      <th>2023</th>\n      <td>60.0</td>\n      <td>40.0</td>\n      <td>17.8</td>\n      <td>13.3</td>\n    </tr>\n    <tr>\n      <th>2024</th>\n      <td>59.5</td>\n      <td>40.5</td>\n      <td>18.9</td>\n      <td>14.4</td>\n    </tr>\n    <tr>\n      <th>2025</th>\n      <td>58.5</td>\n      <td>41.5</td>\n      <td>20.5</td>\n      <td>15.8</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars \n\n::: {#fc6a6033 .cell execution_count=14}\n``` {.python .cell-code}\ncommon_size_is_pl = (\n    inc_pl\n    .sort(\"year\")\n    .with_columns(\n        (\n            pl.exclude(\"year\") / pl.col(\"Revenue\") * 100\n        ).round(1)\n    )\n    .select([\n        \"year\",\n        \"Cost of Goods Sold\",\n        \"Gross Profit\",\n        \"Operating Income\",\n        \"Net Income\",\n    ])\n)\n\ncommon_size_is_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 5)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Cost of Goods Sold</th><th>Gross Profit</th><th>Operating Income</th><th>Net Income</th></tr><tr><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>2021</td><td>62.0</td><td>38.0</td><td>14.7</td><td>10.5</td></tr><tr><td>2022</td><td>61.5</td><td>38.5</td><td>15.8</td><td>11.6</td></tr><tr><td>2023</td><td>60.0</td><td>40.0</td><td>17.8</td><td>13.3</td></tr><tr><td>2024</td><td>59.5</td><td>40.5</td><td>18.9</td><td>14.4</td></tr><tr><td>2025</td><td>58.5</td><td>41.5</td><td>20.5</td><td>15.8</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\nCost of Goods Sold has fallen from 62.0% of revenue in 2021 to 58.5% in 2025 — a steady margin improvement, likely reflecting economies of scale or improved purchasing terms.\n\n::: {.panel-tabset}\n## pandas \n\n::: {#6987e659 .cell execution_count=15}\n``` {.python .cell-code}\nbalance_by_year = bs.set_index(\"year\")\ncommon_size_bs = balance_by_year.div(balance_by_year[\"Total Assets\"], axis=0) * 100\ncommon_size_bs[[\"Cash\", \"Accounts Receivable\", \"Inventory\", \"Property, Plant & Equipment (net)\"]].round(1)\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Cash</th>\n      <th>Accounts Receivable</th>\n      <th>Inventory</th>\n      <th>Property, Plant &amp; Equipment (net)</th>\n    </tr>\n    <tr>\n      <th>year</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2021</th>\n      <td>22.9</td>\n      <td>24.0</td>\n      <td>19.5</td>\n      <td>33.6</td>\n    </tr>\n    <tr>\n      <th>2022</th>\n      <td>31.2</td>\n      <td>21.7</td>\n      <td>17.3</td>\n      <td>29.8</td>\n    </tr>\n    <tr>\n      <th>2023</th>\n      <td>39.5</td>\n      <td>19.4</td>\n      <td>14.9</td>\n      <td>26.2</td>\n    </tr>\n    <tr>\n      <th>2024</th>\n      <td>46.8</td>\n      <td>17.3</td>\n      <td>13.0</td>\n      <td>23.0</td>\n    </tr>\n    <tr>\n      <th>2025</th>\n      <td>53.3</td>\n      <td>15.5</td>\n      <td>11.2</td>\n      <td>20.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars\n\n::: {#860a280b .cell execution_count=16}\n``` {.python .cell-code}\ncommon_size_bs_pl = (\n    bs_pl\n    .sort(\"year\")\n    .with_columns(\n        (\n            pl.exclude(\"year\") / pl.col(\"Total Assets\") * 100\n        ).round(1)\n    )\n    .select([\n        \"year\",\n        \"Cash\",\n        \"Accounts Receivable\",\n        \"Inventory\",\n        \"Property, Plant & Equipment (net)\",\n    ])\n)\n\ncommon_size_bs_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 5)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Cash</th><th>Accounts Receivable</th><th>Inventory</th><th>Property, Plant &amp; Equipment (net)</th></tr><tr><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>2021</td><td>22.9</td><td>24.0</td><td>19.5</td><td>33.6</td></tr><tr><td>2022</td><td>31.2</td><td>21.7</td><td>17.3</td><td>29.8</td></tr><tr><td>2023</td><td>39.5</td><td>19.4</td><td>14.9</td><td>26.2</td></tr><tr><td>2024</td><td>46.8</td><td>17.3</td><td>13.0</td><td>23.0</td></tr><tr><td>2025</td><td>53.3</td><td>15.5</td><td>11.2</td><td>20.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\n::: {.callout-important}\n## Reading the Balance Sheet Structure\nCash has grown from 22.9% to 53.3% of total assets over five years, while receivables, inventory, and PP&E have all *shrunk* as a share of the balance sheet. On its own, this looks like a strong cash position — but as we'll discuss later in this chapter, a rapidly growing cash pile can also raise a legitimate question: is management deploying capital efficiently, or simply letting cash accumulate?\n:::\n\n## Ratio Analysis\n\nRatios distill financial statement data into standardized measures that are comparable across time periods and even across companies. We'll compute four common categories.\n\n### Liquidity Ratios\n\nLiquidity ratios measure a company's ability to meet short-term obligations. Liquidity ratios compare what a business owns against what it owes in the near term. Liquidity ratios include current ratio, quick ratio^[The difference between current ratio and quick ratio is that quick ratio is stricter, excluding inventory because it is the least liquid current asset] (acid-test ratio), and cash ratio. Investors use these ratios to assess if a company is at risk of bankruptcy or financial distress.\n\n:::{.panel-tabset}\n## pandas\n\n::: {#b3d33443 .cell execution_count=17}\n``` {.python .cell-code}\nmerged = inc.merge(bs, on=\"year\")\n\ncurrent_ratio = merged[\"Total Current Assets\"] / merged[\"Total Current Liabilities\"]\nquick_ratio = (merged[\"Cash\"] + merged[\"Accounts Receivable\"]) / merged[\"Total Current Liabilities\"]\n\npd.DataFrame({\"year\": merged[\"year\"], \"Current Ratio\": current_ratio, \"Quick Ratio\": quick_ratio}).round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>Current Ratio</th>\n      <th>Quick Ratio</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2021</td>\n      <td>4.05</td>\n      <td>2.86</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2022</td>\n      <td>4.66</td>\n      <td>3.51</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2023</td>\n      <td>5.52</td>\n      <td>4.41</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2024</td>\n      <td>6.39</td>\n      <td>5.32</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2025</td>\n      <td>7.37</td>\n      <td>6.33</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars\n\n::: {#a308a6fa .cell execution_count=18}\n``` {.python .cell-code}\nratios_pl = (\n    inc_pl\n    .join(bs_pl, on=\"year\", how=\"inner\")\n    .select(\n        \"year\",\n        (\n            pl.col(\"Total Current Assets\")\n            / pl.col(\"Total Current Liabilities\")\n        ).round(2).alias(\"Current Ratio\"),\n        (\n            (pl.col(\"Cash\") + pl.col(\"Accounts Receivable\"))\n            / pl.col(\"Total Current Liabilities\")\n        ).round(2).alias(\"Quick Ratio\"),\n    )\n)\n\nratios_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 3)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Current Ratio</th><th>Quick Ratio</th></tr><tr><td>i64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>2021</td><td>4.05</td><td>2.86</td></tr><tr><td>2022</td><td>4.66</td><td>3.51</td></tr><tr><td>2023</td><td>5.52</td><td>4.41</td></tr><tr><td>2024</td><td>6.39</td><td>5.32</td></tr><tr><td>2025</td><td>7.37</td><td>6.33</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\nA current ratio above 1.0 generally indicates a company can cover its short-term liabilities with short-term assets. Here, both ratios are comfortably above 1.0 and rising every year — worth a closer look later, since *very* high liquidity isn't automatically a good sign either.\n\n### Profitability Ratios\n\nProfitability ratios evaluate a company's ability to generate earnings relative to its revenue, operating costs, assets, and shareholder equity. Generally, higher ratios indicate stronger efficiency, cost control, and financial health.\n\nProfitability ratios are primarily divided into two categories: **Margin Ratios** (which show how much profit is kept from sales) and **Return Ratios** (which show how well resources are used to generate returns for investors). Margin ratios include gross profit margin, operating profit margin, and net profit margin. Return ratios include return on assets (ROA), return on Equity (ROE), and return on invested capital (ROIC). \n\n:::{.panel-tabset}\n## pandas\n\n::: {#4cc14314 .cell execution_count=19}\n``` {.python .cell-code}\ngross_margin = merged[\"Gross Profit\"] / merged[\"Revenue\"]\noperating_margin = merged[\"Operating Income\"] / merged[\"Revenue\"]\nnet_margin = merged[\"Net Income\"] / merged[\"Revenue\"]\nroa = merged[\"Net Income\"] / merged[\"Total Assets\"]\nroe = merged[\"Net Income\"] / merged[\"Total Equity\"]\n\npd.DataFrame({\n    \"year\": merged[\"year\"],\n    \"Gross Margin\": gross_margin,\n    \"Operating Margin\": operating_margin,\n    \"Net Margin\": net_margin,\n    \"ROA\": roa,\n    \"ROE\": roe,\n}).round(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>Gross Margin</th>\n      <th>Operating Margin</th>\n      <th>Net Margin</th>\n      <th>ROA</th>\n      <th>ROE</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2021</td>\n      <td>0.380</td>\n      <td>0.147</td>\n      <td>0.105</td>\n      <td>0.219</td>\n      <td>0.357</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2022</td>\n      <td>0.385</td>\n      <td>0.158</td>\n      <td>0.116</td>\n      <td>0.229</td>\n      <td>0.334</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2023</td>\n      <td>0.400</td>\n      <td>0.178</td>\n      <td>0.133</td>\n      <td>0.242</td>\n      <td>0.321</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2024</td>\n      <td>0.405</td>\n      <td>0.189</td>\n      <td>0.144</td>\n      <td>0.238</td>\n      <td>0.296</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2025</td>\n      <td>0.415</td>\n      <td>0.205</td>\n      <td>0.158</td>\n      <td>0.240</td>\n      <td>0.284</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars \n\n::: {#32c913c3 .cell execution_count=20}\n``` {.python .cell-code}\nmerged_pl = (\n    inc_pl\n    .join(bs_pl, on=\"year\", how=\"inner\")\n)\n```\n:::\n\n\n::: {#d20f3069 .cell execution_count=21}\n``` {.python .cell-code}\nprofitability_ratios = (\n    merged_pl\n    .select(\n        \"year\",\n        (\n            pl.col(\"Gross Profit\") / pl.col(\"Revenue\")\n        ).round(3).alias(\"Gross Margin\"),\n        (\n            pl.col(\"Operating Income\") / pl.col(\"Revenue\")\n        ).round(3).alias(\"Operating Margin\"),\n        (\n            pl.col(\"Net Income\") / pl.col(\"Revenue\")\n        ).round(3).alias(\"Net Margin\"),\n        (\n            pl.col(\"Net Income\") / pl.col(\"Total Assets\")\n        ).round(3).alias(\"ROA\"),\n        (\n            pl.col(\"Net Income\") / pl.col(\"Total Equity\")\n        ).round(3).alias(\"ROE\"),\n    )\n)\n\nprofitability_ratios\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 6)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Gross Margin</th><th>Operating Margin</th><th>Net Margin</th><th>ROA</th><th>ROE</th></tr><tr><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>2021</td><td>0.38</td><td>0.147</td><td>0.105</td><td>0.219</td><td>0.357</td></tr><tr><td>2022</td><td>0.385</td><td>0.158</td><td>0.116</td><td>0.229</td><td>0.334</td></tr><tr><td>2023</td><td>0.4</td><td>0.178</td><td>0.133</td><td>0.242</td><td>0.321</td></tr><tr><td>2024</td><td>0.405</td><td>0.189</td><td>0.144</td><td>0.238</td><td>0.296</td></tr><tr><td>2025</td><td>0.415</td><td>0.205</td><td>0.158</td><td>0.24</td><td>0.284</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\nEvery profitability margin improved steadily from 2021 to 2025. But look closely at **ROE** — despite improving margins, ROE actually *declines* over the same period (35.7% down to 28.4%). This looks contradictory at first glance. We'll resolve exactly why using **DuPont analysis** later in this chapter.\n\n### Leverage Ratios\n\nLeverage ratios measure how much a company relies on debt financing, and its ability to service that debt. By comparing debt to equity, assets, or earnings, these metrics help investors and analysts assess a business's solvency, long-term stability, and overall financial risk. Leverage ratios include debt-to-equity ratio, debt-to-asset ratio, debt-to-EBITDA ratio, and interest coverage ratio.\n\nA **high leverage ratio** indicates a heavy reliance on debt. While this can amplify profits when a company performs well, it also significantly increases the risk of default during economic downturns or periods of low cash flow.  A **low leverage ratio** points to a conservative capital structure with less debt reliance. This often suggests greater financial stability and lower risk of bankruptcy, though it can also signal an inability or reluctance to borrow for growth.\n\nBecause acceptable thresholds vary widely by industry—for example, capital-intensive manufacturing or utility companies naturally require more debt than service-oriented firms—these metrics should always be benchmarked against competitors in the same sector.\n\n::: {.panel-tabset}\n## pandas \n\n::: {#2673d839 .cell execution_count=22}\n``` {.python .cell-code}\ndebt_to_equity = (merged[\"Short-term Debt\"] + merged[\"Long-term Debt\"]) / merged[\"Total Equity\"]\ninterest_coverage = merged[\"Operating Income\"] / merged[\"Interest Expense\"]\n\npd.DataFrame({\n    \"year\": merged[\"year\"],\n    \"Debt-to-Equity\": debt_to_equity,\n    \"Interest Coverage\": interest_coverage,\n}).round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>Debt-to-Equity</th>\n      <th>Interest Coverage</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2021</td>\n      <td>0.43</td>\n      <td>9.98</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2022</td>\n      <td>0.28</td>\n      <td>13.24</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2023</td>\n      <td>0.18</td>\n      <td>18.69</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2024</td>\n      <td>0.11</td>\n      <td>26.20</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2025</td>\n      <td>0.07</td>\n      <td>39.24</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars \n\n::: {#656cd80f .cell execution_count=23}\n``` {.python .cell-code}\nleverage_ratios_pl = (\n    merged_pl\n    .select(\n        \"year\",\n        (\n            (pl.col(\"Short-term Debt\") + pl.col(\"Long-term Debt\"))\n            / pl.col(\"Total Equity\")\n        ).round(2).alias(\"Debt-to-Equity\"),\n        (\n            pl.col(\"Operating Income\")\n            / pl.col(\"Interest Expense\")\n        ).round(2).alias(\"Interest Coverage\"),\n    )\n)\n\nleverage_ratios_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=23}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 3)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Debt-to-Equity</th><th>Interest Coverage</th></tr><tr><td>i64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>2021</td><td>0.43</td><td>9.98</td></tr><tr><td>2022</td><td>0.28</td><td>13.24</td></tr><tr><td>2023</td><td>0.18</td><td>18.69</td></tr><tr><td>2024</td><td>0.11</td><td>26.2</td></tr><tr><td>2025</td><td>0.07</td><td>39.24</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\nDebt-to-equity has fallen sharply (from 0.43 to 0.18), and interest coverage has risen from about 10x to nearly 40x — the company has been paying down debt aggressively while growing operating income, substantially reducing its financial risk.\n\n### Efficiency Ratios\n\nEfficiency ratios measure how well a company uses its assets to generate revenue. They compare a company’s expenses to its sales or track how quickly it turns assets into cash. Higher turnover ratios and lower expense ratios usually signal strong operational health. Efficiency ratios include asset turnover ratio, inventory turnover ratio, and accounts receivable turnover ratio.\n\n:::{.panel-tabset}\n## pandas \n\n::: {#808e39c6 .cell execution_count=24}\n``` {.python .cell-code}\nasset_turnover = merged[\"Revenue\"] / merged[\"Total Assets\"]\ndso = merged[\"Accounts Receivable\"] / merged[\"Revenue\"] * 365\ndio = merged[\"Inventory\"] / merged[\"Cost of Goods Sold\"] * 365\n\npd.DataFrame({\n    \"year\": merged[\"year\"],\n    \"Asset Turnover\": asset_turnover,\n    \"Days Sales Outstanding\": dso,\n    \"Days Inventory Outstanding\": dio,\n}).round(1)\n```\n\n::: {.cell-output .cell-output-display execution_count=24}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>Asset Turnover</th>\n      <th>Days Sales Outstanding</th>\n      <th>Days Inventory Outstanding</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2021</td>\n      <td>2.1</td>\n      <td>42.0</td>\n      <td>55.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2022</td>\n      <td>2.0</td>\n      <td>40.0</td>\n      <td>52.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2023</td>\n      <td>1.8</td>\n      <td>39.0</td>\n      <td>50.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2024</td>\n      <td>1.7</td>\n      <td>38.0</td>\n      <td>48.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2025</td>\n      <td>1.5</td>\n      <td>37.0</td>\n      <td>46.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars \n\n::: {#ed3ee8f9 .cell execution_count=25}\n``` {.python .cell-code}\nasset_efficiency_pl = (\n    merged_pl\n    .select(\n        \"year\",\n        (\n            pl.col(\"Revenue\")\n            / pl.col(\"Total Assets\")\n        ).round(1).alias(\"Asset Turnover\"),\n        (\n            pl.col(\"Accounts Receivable\")\n            / pl.col(\"Revenue\")\n            * 365\n        ).round(1).alias(\"Days Sales Outstanding\"),\n        (\n            pl.col(\"Inventory\")\n            / pl.col(\"Cost of Goods Sold\")\n            * 365\n        ).round(1).alias(\"Days Inventory Outstanding\"),\n    )\n)\n\nasset_efficiency_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 4)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Asset Turnover</th><th>Days Sales Outstanding</th><th>Days Inventory Outstanding</th></tr><tr><td>i64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>2021</td><td>2.1</td><td>42.0</td><td>55.0</td></tr><tr><td>2022</td><td>2.0</td><td>40.0</td><td>52.0</td></tr><tr><td>2023</td><td>1.8</td><td>39.0</td><td>50.0</td></tr><tr><td>2024</td><td>1.7</td><td>38.0</td><td>48.0</td></tr><tr><td>2025</td><td>1.5</td><td>37.0</td><td>46.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\nDays Sales Outstanding and Days Inventory Outstanding have both **improved** (fallen) — the company collects receivables faster and turns over inventory faster in 2025 than in 2021. Yet asset turnover has *declined* (from 2.09 down to 1.53) — total assets are growing even faster than revenue, largely because of that growing cash balance. This is another thread we'll pick up in the DuPont section.\n\n## Automating Ratio Calculations\n\nRather than recomputing each ratio by hand every time you get a new year of data, it's worth writing a single reusable function.\n\n:::{.panel-tabset}\n## pandas \n\n::: {#3d2704cd .cell execution_count=26}\n``` {.python .cell-code}\ndef compute_ratios(income_df: pd.DataFrame, balance_df: pd.DataFrame) -> pd.DataFrame:\n    \"\"\"Compute standard liquidity, profitability, leverage, and efficiency ratios\n    from an income statement and balance sheet sharing a common 'year' column.\"\"\"\n    df = income_df.merge(balance_df, on=\"year\")\n    r = pd.DataFrame({\"year\": df[\"year\"]})\n\n    # Liquidity\n    r[\"Current Ratio\"] = df[\"Total Current Assets\"] / df[\"Total Current Liabilities\"]\n    r[\"Quick Ratio\"] = (df[\"Cash\"] + df[\"Accounts Receivable\"]) / df[\"Total Current Liabilities\"]\n\n    # Profitability\n    r[\"Gross Margin\"] = df[\"Gross Profit\"] / df[\"Revenue\"]\n    r[\"Operating Margin\"] = df[\"Operating Income\"] / df[\"Revenue\"]\n    r[\"Net Margin\"] = df[\"Net Income\"] / df[\"Revenue\"]\n    r[\"Return on Assets\"] = df[\"Net Income\"] / df[\"Total Assets\"]\n    r[\"Return on Equity\"] = df[\"Net Income\"] / df[\"Total Equity\"]\n\n    # Leverage\n    r[\"Debt-to-Equity\"] = (df[\"Short-term Debt\"] + df[\"Long-term Debt\"]) / df[\"Total Equity\"]\n    r[\"Interest Coverage\"] = df[\"Operating Income\"] / df[\"Interest Expense\"]\n\n    # Efficiency\n    r[\"Asset Turnover\"] = df[\"Revenue\"] / df[\"Total Assets\"]\n    r[\"Days Sales Outstanding\"] = df[\"Accounts Receivable\"] / df[\"Revenue\"] * 365\n    r[\"Days Inventory Outstanding\"] = df[\"Inventory\"] / df[\"Cost of Goods Sold\"] * 365\n\n    return r.set_index(\"year\")\n```\n:::\n\n\n::: {#3a23317e .cell execution_count=27}\n``` {.python .cell-code}\nratios = compute_ratios(inc, bs)\nratios.round(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=27}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Current Ratio</th>\n      <th>Quick Ratio</th>\n      <th>Gross Margin</th>\n      <th>Operating Margin</th>\n      <th>Net Margin</th>\n      <th>Return on Assets</th>\n      <th>Return on Equity</th>\n      <th>Debt-to-Equity</th>\n      <th>Interest Coverage</th>\n      <th>Asset Turnover</th>\n      <th>Days Sales Outstanding</th>\n      <th>Days Inventory Outstanding</th>\n    </tr>\n    <tr>\n      <th>year</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2021</th>\n      <td>4.054</td>\n      <td>2.864</td>\n      <td>0.380</td>\n      <td>0.147</td>\n      <td>0.105</td>\n      <td>0.219</td>\n      <td>0.357</td>\n      <td>0.430</td>\n      <td>9.984</td>\n      <td>2.088</td>\n      <td>42.0</td>\n      <td>55.0</td>\n    </tr>\n    <tr>\n      <th>2022</th>\n      <td>4.659</td>\n      <td>3.508</td>\n      <td>0.385</td>\n      <td>0.158</td>\n      <td>0.116</td>\n      <td>0.229</td>\n      <td>0.334</td>\n      <td>0.283</td>\n      <td>13.241</td>\n      <td>1.980</td>\n      <td>40.0</td>\n      <td>52.0</td>\n    </tr>\n    <tr>\n      <th>2023</th>\n      <td>5.521</td>\n      <td>4.406</td>\n      <td>0.400</td>\n      <td>0.178</td>\n      <td>0.133</td>\n      <td>0.242</td>\n      <td>0.321</td>\n      <td>0.181</td>\n      <td>18.692</td>\n      <td>1.814</td>\n      <td>39.0</td>\n      <td>50.0</td>\n    </tr>\n    <tr>\n      <th>2024</th>\n      <td>6.395</td>\n      <td>5.317</td>\n      <td>0.405</td>\n      <td>0.189</td>\n      <td>0.144</td>\n      <td>0.238</td>\n      <td>0.296</td>\n      <td>0.113</td>\n      <td>26.205</td>\n      <td>1.659</td>\n      <td>38.0</td>\n      <td>48.0</td>\n    </tr>\n    <tr>\n      <th>2025</th>\n      <td>7.369</td>\n      <td>6.333</td>\n      <td>0.415</td>\n      <td>0.205</td>\n      <td>0.158</td>\n      <td>0.240</td>\n      <td>0.284</td>\n      <td>0.068</td>\n      <td>39.236</td>\n      <td>1.525</td>\n      <td>37.0</td>\n      <td>46.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars \n\n::: {#3b87743e .cell execution_count=28}\n``` {.python .cell-code}\ndef compute_ratios_pl(income_df: pl.DataFrame, balance_df: pl.DataFrame) -> pl.DataFrame:\n    \"\"\"Compute standard liquidity, profitability, leverage, and efficiency ratios\n    from an income statement and balance sheet sharing a common 'year' column.\"\"\"\n\n    df = income_df.join(balance_df, on=\"year\", how=\"inner\")\n\n    r = df.select(\n        \"year\",\n\n        # Liquidity\n        (\n            pl.col(\"Total Current Assets\")\n            / pl.col(\"Total Current Liabilities\")\n        ).alias(\"Current Ratio\"),\n\n        (\n            (pl.col(\"Cash\") + pl.col(\"Accounts Receivable\"))\n            / pl.col(\"Total Current Liabilities\")\n        ).alias(\"Quick Ratio\"),\n\n\n        # Profitability\n        (\n            pl.col(\"Gross Profit\")\n            / pl.col(\"Revenue\")\n        ).alias(\"Gross Margin\"),\n\n        (\n            pl.col(\"Operating Income\")\n            / pl.col(\"Revenue\")\n        ).alias(\"Operating Margin\"),\n\n        (\n            pl.col(\"Net Income\")\n            / pl.col(\"Revenue\")\n        ).alias(\"Net Margin\"),\n\n        (\n            pl.col(\"Net Income\")\n            / pl.col(\"Total Assets\")\n        ).alias(\"Return on Assets\"),\n\n        (\n            pl.col(\"Net Income\")\n            / pl.col(\"Total Equity\")\n        ).alias(\"Return on Equity\"),\n\n\n        # Leverage\n        (\n            (pl.col(\"Short-term Debt\") + pl.col(\"Long-term Debt\"))\n            / pl.col(\"Total Equity\")\n        ).alias(\"Debt-to-Equity\"),\n\n        (\n            pl.col(\"Operating Income\")\n            / pl.col(\"Interest Expense\")\n        ).alias(\"Interest Coverage\"),\n\n\n        # Efficiency\n        (\n            pl.col(\"Revenue\")\n            / pl.col(\"Total Assets\")\n        ).alias(\"Asset Turnover\"),\n\n        (\n            pl.col(\"Accounts Receivable\")\n            / pl.col(\"Revenue\")\n            * 365\n        ).alias(\"Days Sales Outstanding\"),\n\n        (\n            pl.col(\"Inventory\")\n            / pl.col(\"Cost of Goods Sold\")\n            * 365\n        ).alias(\"Days Inventory Outstanding\"),\n    )\n\n    return r\n```\n:::\n\n\n::: {#e514cb72 .cell execution_count=29}\n``` {.python .cell-code}\nratios_pl = compute_ratios_pl(inc_pl, bs_pl)\n\nratios_pl = ratios_pl.with_columns(\n    pl.exclude(\"year\").round(3)\n)\n\nratios_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=29}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 13)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Current Ratio</th><th>Quick Ratio</th><th>Gross Margin</th><th>Operating Margin</th><th>Net Margin</th><th>Return on Assets</th><th>Return on Equity</th><th>Debt-to-Equity</th><th>Interest Coverage</th><th>Asset Turnover</th><th>Days Sales Outstanding</th><th>Days Inventory Outstanding</th></tr><tr><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>2021</td><td>4.054</td><td>2.864</td><td>0.38</td><td>0.147</td><td>0.105</td><td>0.219</td><td>0.357</td><td>0.43</td><td>9.984</td><td>2.088</td><td>42.0</td><td>55.0</td></tr><tr><td>2022</td><td>4.659</td><td>3.508</td><td>0.385</td><td>0.158</td><td>0.116</td><td>0.229</td><td>0.334</td><td>0.283</td><td>13.241</td><td>1.98</td><td>40.0</td><td>52.0</td></tr><tr><td>2023</td><td>5.521</td><td>4.406</td><td>0.4</td><td>0.178</td><td>0.133</td><td>0.242</td><td>0.321</td><td>0.181</td><td>18.692</td><td>1.814</td><td>39.0</td><td>50.0</td></tr><tr><td>2024</td><td>6.395</td><td>5.317</td><td>0.405</td><td>0.189</td><td>0.144</td><td>0.238</td><td>0.296</td><td>0.113</td><td>26.205</td><td>1.659</td><td>38.0</td><td>48.0</td></tr><tr><td>2025</td><td>7.369</td><td>6.333</td><td>0.415</td><td>0.205</td><td>0.158</td><td>0.24</td><td>0.284</td><td>0.068</td><td>39.236</td><td>1.525</td><td>37.0</td><td>46.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\n\n\n::: {.callout-tip}\n## Connect to Practice\nWriting analysis as a reusable function like this — rather than one-off code you rerun and edit each period — is exactly how analytics work scales in practice. Next quarter's financial statements can be run through the same `compute_ratios()` function with zero changes, as long as the column names match. This is also foreshadows the automated reporting techniques in Chapter 14.\n:::\n\n## DuPont Decomposition: Explaining *Why* ROE Changed\n\nThe DuPont framework breaks **return on equity (ROE)** into three multiplied components, each capturing a different lever of performance:\n\n\n$$\n\\text{ROE} = \\underbrace{\\frac{\\text{Net Income}}{\\text{Revenue}}}_{\\text{Net Margin}} \\times \\underbrace{\\frac{\\text{Revenue}}{\\text{Total Assets}}}_{\\text{Asset Turnover}} \\times \\underbrace{\\frac{\\text{Total Assets}}{\\text{Total Equity}}}_{\\text{Equity Multiplier}}\n$$\n\n:::{.panel-tabset}\n## pandas \n\n::: {#1cbc1fee .cell execution_count=30}\n``` {.python .cell-code}\ndupont = pd.DataFrame({\"year\": merged[\"year\"]})\ndupont[\"Net Margin\"] = merged[\"Net Income\"] / merged[\"Revenue\"]\ndupont[\"Asset Turnover\"] = merged[\"Revenue\"] / merged[\"Total Assets\"]\ndupont[\"Equity Multiplier\"] = merged[\"Total Assets\"] / merged[\"Total Equity\"]\ndupont[\"ROE (DuPont)\"] = dupont[\"Net Margin\"] * dupont[\"Asset Turnover\"] * dupont[\"Equity Multiplier\"]\n\ndupont.set_index(\"year\").round(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=30}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Net Margin</th>\n      <th>Asset Turnover</th>\n      <th>Equity Multiplier</th>\n      <th>ROE (DuPont)</th>\n    </tr>\n    <tr>\n      <th>year</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2021</th>\n      <td>0.105</td>\n      <td>2.088</td>\n      <td>1.633</td>\n      <td>0.357</td>\n    </tr>\n    <tr>\n      <th>2022</th>\n      <td>0.116</td>\n      <td>1.980</td>\n      <td>1.458</td>\n      <td>0.334</td>\n    </tr>\n    <tr>\n      <th>2023</th>\n      <td>0.133</td>\n      <td>1.814</td>\n      <td>1.328</td>\n      <td>0.321</td>\n    </tr>\n    <tr>\n      <th>2024</th>\n      <td>0.144</td>\n      <td>1.659</td>\n      <td>1.241</td>\n      <td>0.296</td>\n    </tr>\n    <tr>\n      <th>2025</th>\n      <td>0.158</td>\n      <td>1.525</td>\n      <td>1.180</td>\n      <td>0.284</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## polars \n\n::: {#cd9a8e5e .cell execution_count=31}\n``` {.python .cell-code}\ndupont_pl = (\n    merged_pl\n    .select(\n        \"year\",\n\n        (\n            pl.col(\"Net Income\") / pl.col(\"Revenue\")\n        ).alias(\"Net Margin\"),\n\n        (\n            pl.col(\"Revenue\") / pl.col(\"Total Assets\")\n        ).alias(\"Asset Turnover\"),\n\n        (\n            pl.col(\"Total Assets\") / pl.col(\"Total Equity\")\n        ).alias(\"Equity Multiplier\"),\n\n        (\n            (pl.col(\"Net Income\") / pl.col(\"Revenue\"))\n            *\n            (pl.col(\"Revenue\") / pl.col(\"Total Assets\"))\n            *\n            (pl.col(\"Total Assets\") / pl.col(\"Total Equity\"))\n        ).alias(\"ROE (DuPont)\"),\n    )\n    .with_columns(\n        pl.exclude(\"year\").round(3)\n    )\n)\n\ndupont_pl\n```\n\n::: {.cell-output .cell-output-display execution_count=31}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (5, 5)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>year</th><th>Net Margin</th><th>Asset Turnover</th><th>Equity Multiplier</th><th>ROE (DuPont)</th></tr><tr><td>i64</td><td>f64</td><td>f64</td><td>f64</td><td>f64</td></tr></thead><tbody><tr><td>2021</td><td>0.105</td><td>2.088</td><td>1.633</td><td>0.357</td></tr><tr><td>2022</td><td>0.116</td><td>1.98</td><td>1.458</td><td>0.334</td></tr><tr><td>2023</td><td>0.133</td><td>1.814</td><td>1.328</td><td>0.321</td></tr><tr><td>2024</td><td>0.144</td><td>1.659</td><td>1.241</td><td>0.296</td></tr><tr><td>2025</td><td>0.158</td><td>1.525</td><td>1.18</td><td>0.284</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n:::\nThis confirms exactly the same ROE figures as the direct calculation earlier — but now we can see *why* ROE fell even as profitability rose:\n\n- **Net Margin improved** (10.5% → 15.8%) — profitability genuinely got better.\n- **Asset Turnover fell** (2.09 → 1.53) — assets (mostly that growing cash pile) grew faster than revenue.\n- **Equity Multiplier fell** (1.63 → 1.18) — the company relies on much less debt financing than before.\n\nThe margin improvement was real, but it was **more than offset** by the combined effect of falling asset turnover and falling leverage. In other words: the company is becoming more profitable per dollar of sales, but less efficient at *using* its (growing) asset base, and increasingly equity-financed rather than debt-financed — both of which mechanically pull ROE down, even while the business is arguably getting healthier in other respects.\n\n::: {.callout-important}\n## Why This Matters\nReporting \"ROE declined from 35.7% to 28.4%\" without DuPont context could easily be read as bad news. DuPont decomposition shows that the *decline* is actually a byproduct of paying down debt and building cash reserves — both generally prudent financial decisions — rather than declining profitability. This is a good example of why a single ratio, in isolation, can mislead; understanding its components tells the real story.\n:::\n\n## Visualizing the Trends\n\nA trend that takes several tables to describe in words is often obvious in one chart.\n\n::: {.panel-tabset}\n## seaborn\n\n::: {#671903e0 .cell execution_count=32}\n``` {.python .cell-code}\nimport seaborn as sns\nimport matplotlib.pyplot as plt\nimport matplotlib.ticker as mticker\n\nmargin_long = ratios.reset_index()[[\"year\", \"Gross Margin\", \"Operating Margin\", \"Net Margin\"]].melt(\n    id_vars=\"year\", var_name=\"Margin Type\", value_name=\"Value\"\n)\n\nplt.figure(figsize=(7, 4.5))\nsns.lineplot(data=margin_long, x=\"year\", y=\"Value\", hue=\"Margin Type\", marker=\"o\")\nplt.title(\"Margin Trends, 2021-2025\")\nplt.ylabel(\"Margin (% of Revenue)\")\nplt.gca().yaxis.set_major_formatter(mticker.PercentFormatter(1.0))\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](07-financial-statement-analysis_files/figure-epub/cell-33-output-1.png){}\n:::\n:::\n\n\n## plotnine\n\n::: {#99b5afa2 .cell execution_count=33}\n``` {.python .cell-code}\nfrom plotnine import *\n\n(\n    ggplot(margin_long, aes(x=\"year\", y=\"Value\", color=\"Margin Type\"))\n    + geom_line(size=1)\n    + geom_point()\n    + scale_y_continuous(labels=lambda l: [f\"{v:.0%}\" for v in l])\n    + labs(title=\"Margin Trends, 2021-2025\", x=\"Year\", y=\"Margin (% of Revenue)\")\n    + theme_minimal()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=33}\n![](07-financial-statement-analysis_files/figure-epub/cell-34-output-1.png){width=240 height=192}\n:::\n:::\n\n\n:::\n\nAll three margins trend upward and roughly in parallel — visual confirmation that the profitability improvement is broad-based (starting at the gross profit level) rather than coming from just one line item, like a one-time tax benefit.\n\n::: {#b8344617 .cell execution_count=34}\n``` {.python .cell-code}\nplt.figure(figsize=(7, 4.5))\nsns.lineplot(data=dupont, x=\"year\", y=\"ROE (DuPont)\", marker=\"o\", color=\"#8a4fbe\")\nplt.title(\"Return on Equity, 2021-2025\")\nplt.ylabel(\"ROE\")\nplt.gca().yaxis.set_major_formatter(mticker.PercentFormatter(1.0))\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](07-financial-statement-analysis_files/figure-epub/cell-35-output-1.png){}\n:::\n:::\n\n\nSeeing the steady ROE decline plotted directly against the improving margins from the chart above makes the apparent contradiction visually obvious — exactly the kind of pattern that should prompt a DuPont-style investigation rather than a surface-level \"ROE is getting worse\" conclusion.\n\n## Putting It Together: A Financial Health Memo\n\nA typical output of this kind of analysis isn't just a table of ratios — it's a short written interpretation for a decision-maker. Here's a brief example, written the way you might summarize this exact analysis for a manager:\n\n::: {.callout-tip}\n## Sample Memo Excerpt\n*Ledger & Co.'s profitability has improved steadily over the past five years, with net margin rising from 10.5% to 15.8%, driven by both improving gross margins and declining interest expense. The company has also meaningfully reduced financial risk, cutting debt-to-equity from 0.43 to 0.18 while more than tripling interest coverage. Return on equity has declined over the same period (35.7% to 28.4%), but DuPont analysis attributes this to the combined effect of debt paydown and a growing cash balance — both generally prudent — rather than any underlying weakness in operations. One area worth management's attention: the current ratio has risen to 7.4x, well above what's typically needed for liquidity purposes, suggesting cash may be accumulating faster than it's being deployed into growth, debt reduction, or shareholder returns.*\n:::\n\nNotice that this memo doesn't just repeat the numbers — it interprets what they mean *together*, flags a genuine open question (the growing cash pile) rather than treating every metric as unambiguously good news, and avoids the trap of reporting the ROE decline without its DuPont explanation.\n\n## Chapter Summary\n\n- Horizontal analysis compares a line item across time (dollar and percent change, or indexed to a base year); vertical (common-size) analysis expresses every line item as a percentage of a base figure within the same year.\n- Liquidity, profitability, leverage, and efficiency ratios each capture a different dimension of financial performance, and no single ratio tells the whole story on its own.\n- Wrapping ratio calculations in a reusable function (like `compute_ratios()`) means the same analysis can be rerun on any future period's data without rewriting code.\n- DuPont decomposition breaks ROE into net margin, asset turnover, and equity multiplier — essential for explaining *why* ROE changed, not just that it did, and for avoiding misleading single-ratio conclusions.\n- A rising ratio isn't automatically good news (e.g., an extremely high current ratio can signal underused cash) any more than a falling ratio is automatically bad news (e.g., falling ROE driven by prudent deleveraging) — ratio analysis requires interpretation, not just calculation.\n\n## Discussion Questions\n\n1. Ledger & Co.'s current ratio rose from 4.05 to 7.37 over five years. At what point, if any, does \"more liquidity\" stop being a good thing? What would you want to know before deciding?\n2. Explain in your own words why ROE declined even though every margin (gross, operating, net) improved over the same period.\n3. If you were advising this company's CFO, what would you recommend they consider doing with the growing cash balance, and what additional information would you want before making that recommendation?\n\n## Exercises\n\n1. Using `compute_ratios()`, add one additional ratio of your choice (e.g., **Return on Invested Capital**, **Cash Ratio**, or **Fixed Asset Turnover**) and compute it for all five years.\n2. Perform vertical analysis on the *liabilities and equity* side of the balance sheet (not just assets, which this chapter covered). How has the company's financing mix shifted between 2021 and 2025?\n3. Recreate the margin trend chart from this chapter, but plot Return on Assets and Return on Equity together instead of the three margins. What does the widening or narrowing gap between ROA and ROE tell you about leverage over time?\n4. Write your own 150-word financial health memo based on the leverage and efficiency ratios computed in this chapter (rather than the profitability-focused example memo shown above).\n\n",
    "supporting": [
      "07-financial-statement-analysis_files\\figure-epub"
    ],
    "filters": [],
    "engineDependencies": {
      "jupyter": [
        {
          "jsWidgets": true,
          "jupyterWidgets": false,
          "htmlLibraries": []
        }
      ]
    }
  }
}